//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarRaider.GPMDP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgNoToken {
            get {
                return ((string)(this["ImgNoToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgNoConnection {
            get {
                return ((string)(this["ImgNoConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjQzLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0ODozNS0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0ODo" +
            "zNS0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpjNDY3YWRlMy1kNjEwLTk5NGEtYmU1ZC1kZDAxMmNhMjQ1OWYiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6YzQ2N2FkZTMtZDYxMC05OTRhLWJlNWQtZGQwMTJjYTI0NTlmIiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6YzQ2N2FkZTMtZDYxMC05OTRhLWJlNWQtZGQwMTJjYTI0NTlmIj4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDpjNDY3YWRlMy1kNjEwLTk5NGEtYmU1ZC1kZDAxMmNhMjQ1OWYiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6NDMtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz6C0IE1AAAQrklEQVR4nO2dX3QUVZ7Hv7e6uqu76U66k6ZDEgMYmF1BEBOyEQb5sxIFxyPggOw" +
            "57qqjMj6A/FsCPMxxXzz7gJBBQNhzEP8wszN7DgoKji444OHvilkIIgjOChGJTUjoJJ10p/933X2odHe" +
            "UQEhVJ1033M9TJ52q+v2qPrn31q1b9xJogFJKwm9YH4rH6BMASkFRRIEiQlBIKbVr2TcnsxBC/JSikQD" +
            "XQHANQL1oJJ+YVwS/JIRQ1ftVs1GwRqqKJ/A0KJkD0GFqD87RA+Q6CN0nGvC+dVXkYJ+37ssfhzZaJiX" +
            "i8uuyjKl9PRBH/wgCjhlEYY1lZejknW5zRwIFa6TSuEzWQ6a/Vh8ehxkEskcU6Grrqkh9b3/aq0DBGqk" +
            "qHscuAM6MBMdhhTZRxMLeqjXhdl92bJCWygnsB5fnbsQpJ7C/Y4O09HZ/dMsSKLBeekOWsTzzcXFYQxC" +
            "wybY6sqKn73oUqGODtBQJbO7XqDhsYcCynOrIlp//+iaBgjVSlZzAfpnCMDCRcVhAIEgIBsz+eZvoJwI" +
            "Fa6TSeBynwNs8nJ5pE0VUdL87+0kjOi6T9eDycG6Ns8uRFKkSKLTRMikWlb8Y+Jg4rGE0CZOTnY2pEig" +
            "Rl1/PXkgclujuigB0NZz54wnOHSLLmBqskaqALoHiCTyd3ZA4rJF0RqCUEuWpOofTByiZQyklhDeeOWo" +
            "xmoTJQtdgMA6nz8Rj9AkBQGm2A+EwS6kAiqJsR8FhFIoigYILxFEHBYoEQlCY7UA4bEIICgX+9gRHLZR" +
            "S+21HJHI4vcEF4miCC8TRBBeIowkuEEcTXCCOJrhAHE1wgTia4AJxNMEF4miCC8TRBBeIowkuEEcTXCC" +
            "OJrhAHE1wgTia4AJxNCFmO4Bs4w0b8FmzHbV+Cy74RDQ3JxDxJ4BwHHIwDgAQrCJgFiHZDXC7DRjriKP" +
            "SHsJjbj9c5kSWM8gupGOdpHqSaVY55TXjzYZ81F2SEbkS0LQvaaQN5aMFvFLSggpXOEMRssNdI1AwRrD" +
            "u8lDsPisgdrUz9XtiNiDvPjseKEhgvD2MMlsIxeY4bMYEckzKqemIEgRiBnjCIs4ELDjnN+PrJgNav/W" +
            "DhtMlkHH4EMyfIGPtqBuwGu+K0zr4BeqICHj1UgEOHIuA+mMAAOKUUDnRjBeLWzHFFYJRUHcKYjLBCa8" +
            "F73jyUHs6DNoWUfZvN2LWVAmvjW5CjiRnLBc9MqgF2lKfh62HCKgvCgDIGZeLteM78FSxHwb1y0P0SII" +
            "SfOixY925HHScbwcAEIcJS2ZSLC1tzeix9MSgFKghYMC8w4UIXFQuZM64XGwob8H0gtCAHP9IkwXVdfk" +
            "pkWxjcvHRjEaU2AZfg3vQCXS0yYqXP7aCtkVAXGZUPxLHohFtWYllxw9ObPhcBPWGQZwStj8ZxLSCYFZ" +
            "i6S8GlUCb6vOxbV8ciMnIL3fgwDQP7MbstkH8MQGzjhajpc4HGAUsniNieWlLVmPKJIOiI1GmwPNnirF" +
            "tdxSIyZhUlYMTVQ1ZlwcA7EYZJ6oaMKkqB4jJ2LY7iufPFEMeJP+2zAskU2D64RKcPNgBGAUsW2DEzjI" +
            "PMtxG1gShwM4yD5YtMAJGAScPdmD64ZJBIRHzAr3wVTGaT/lAHCa8/UwUS+7V7x3Pkntb8fYzURCHCc2" +
            "nfHjhq+Jsh6QZpgXaVJ+fKnl2zA3iYffA3GVp4WF3CDvmBlMl0ab6/GyHpAlmBTraZFUazACWzTUwIU+" +
            "Sh90hLJurLEWybV8cR5usWY5IPUwK1BAw4OWPrakGs56rrVux5N7WVMP65Y+taAiwubYNkwLNO1wI2hZ" +
            "BfrkD75V7sh2Oat4r9yC/3AHaFsG8w2zO88WcQFvq8xC42A7iMuPANH3dbfUVQqHk4DIjcLEdW+rzsh1" +
            "Sn2FKoI6IgK2HlPVhqh+J66KfRyt2o4zqR5S23NZDBB0Rpi4JWwK9eqkA1BdFzrjcfn880dgp4pm6ezB" +
            "hT1G/lwyLRrQhZ1wuqC+KVy8V9OuxMg0zAgVjBAeOKcMlNpT336OAYJRg2fkizHjXjtOH2hG+7MfWw/3" +
            "fwE3mdOBYBMHYHa3GrguYEWjd5aGg/hhyxuX2y1N1SoBNl/NR/icXDvy3HwjF09+19P9Iw+kFIaUU8se" +
            "w7vLQfj9epmBGoN1nlVDXju/I+L4/abRhwq5CbNsTBfX2TZaZx4bjvrfyseqbYaAaC45kbslcWYCJSE9" +
            "5zYhd7QTJk/BUsT9j+z3XJuGXfy3Bv/4nUT02uulaFNQXxV8+7cSTXwzXFM9TxX4Qp4TY1U6c8po17Wu" +
            "gYEKgNxuU7v7KcnNGRhI2doqYV1uCBW+b0PKVr0/bPnp8OMZsz8fWrob1bytiqe++O9aGmksu1XEZCEX" +
            "lREWcZM56hwmB6i4pt+svFmvrce7eQL54xAeocPHqWT/k9ig274nhUNMQLB/VgoIKR+r77fsT+K7dqDr" +
            "GZI7JnPWO7gXyhg2IXAmAmA2Y4lLfeL5VA7mvlE8aonygwPLDdmUs9GQPBFdXlROK47kv1d+KT3GFQMx" +
            "Kzt6w/h9v6F6gz5qVlRjy7rOrfnsCgKoGck/8xzgPhFwTACB2tRO/v5yPfLOM1x5N77v1bDtqb1hU7d8" +
            "oUDj/3gYgnbue0b1AtX7lQjxQcOcD0mMywY4fnCjbm/nxNg6J4tl/TJ+2P55RqqsF9/hhGZ2+4NXn1be" +
            "FJgxTqq9k7npG9wJd8ClvX4+39156NHWKWP5NIca/58L6XXEE/y/zt/wAsGKEF7AqcUWuBHDSq1zoNRP" +
            "TA+ab6trRrvKxRDLXZO56RvcCNTcrJU+Z7fbtn3//zo1pbw3B/k8D/d7xZzVR/N1EW+rn3TdyAQALitt" +
            "BzF3tFplib1OOqv0nc03mrmd0L1DErzR4i823b/j+4YAyoH6geLwg/Xr0CY9SjZkMFK7709XYnuvq2jD" +
            "JXCN+LpB2ut49txl7OZmhgT3Z0x1pgTqa031BkwvTnxua1AmdyjWs/m5xoNC9QMkpVpITHegFd7dpXWL" +
            "t0dTnkeb053C7OgGSuSZz1zO6F0iv2IzdLm63kqK7QImuyRYGM7oXSOi62+mI6muIQ3s03clH7KbU5zh" +
            "Nn1IqqIs5mWsydz2je4FgVk5iINZLr6xlYHttLwXS0phy048uroTTn41OSdW+U7mauUCakezKyfSEb38" +
            "yn5tlAowDl85nrelb9HvuScd2JZQWy5yrToBkrsnc9YzuBXK7lZN4JnD7Xtnf/aIZR3/bidm/soHk9/9" +
            "QiP1X0iXNzG7vpH3hSUtzr1vdvpO5JnPXM7ovI8c64vgBwDl/71IUDIlj0/2NiI0h2NngwNavrAAyN34" +
            "oyZUOI9rPKXP/wEDwbJEPgPK0v+1Cuvf7nwrbVe1fyTWGsQ5+F6aZSrvy3/11053/NxoFikUj2nBmbv+" +
            "8M/bKhfQ7XO6yXLgtyoX+o8eZ7sw0Cpjt7uxp8145e125LMnc9YzuBXrMrZQgrd/6EZPV34kt/rUJxKW" +
            "9arvok/Dd8fQbITXjvACUMdVbvky3f0b8Qw5spr53JMZkgra/KaMjk7nrGd0L5DInII20gYYTOOFV/3R" +
            "6+agW1P2zF7N/ZQMs6mvuP113pAaijfilE5VDlVLirfo8xBrSJc7Gsc2q9n/CawENKzmzMAe17gUCgPL" +
            "RSpjveLS9n2U1UWy6vxGHX/BjzHQHoKJAm+/ygTgl5I7PxQcVPwIAPJ0GbPxremdFDzlxv1NdJ2Iyx2T" +
            "OeoeJKF8pUd6Zqj0dRkLrqw8ACofE8VFlAz54KYr8Bx192rbMFcG3i7yonf0jciQZlADzjhZC7nqcQXK" +
            "M+K8KdW2vBCWoPa2MJEjmrHeYEKjCFYZx+BDQtgg+9GRulN54ZwT/82gDfv8vFNJIW+8b9MDvLg5LzcY" +
            "KAP/2uIxhVnVVz4ceO2hbBMbhQ5iZ9Z4JgQBg/gSlQbrunLoxNrfjicIAzi5sVNXQ3vNFWpbJVTl4Zrh" +
            "PdRzJ3JK5sgAzAq0ddQPEbkTH+XYcacr8UE9Cb93Qvp1UjmIziMuMZ+da8F6Z+m6DI00WdJxvB7EbsXb" +
            "UDdX7GWh035GYxGqkmDVVwv5PY6iuy8f/Pv5j/xynq6HdOFLEqr8NwzdXZLz84K2rk5OPNWTkuNV1+QD" +
            "aMWuqxNQ6G0zNE90REVD5ByeoL4rVC8WsTSCeaXb84MT6XXEQhwm1z7Uxtb4GM1UYAORIMpbMVHzf8Lk" +
            "If4yp8HvEHxOw4XOlIlgykzIlD8CYQACwtLQVtjG5oN4wZh0t1jyhQTahBEoO3jBsY3KZXJSFOYEA4KM" +
            "ZjSBOCS11Pvymjt25ln9TpyyBQJwSPprRmO1wVMGkQCW2BLY/mZ5reev37M0tuPX7vNQc19ufDDK7kg+" +
            "TAgHAtIIgFs9R2g6b9yZwvFn/b3EmOd5swea9ijCL54hMr+DDrEAAsLy0JTXX8qK9ViYkOt5swaK96Tm" +
            "uWV+5h2mBAODdBz1wVzhAfVG89GeTrquzrd/n4aU/m0B9UbgrHHj3QXbnuE7CvEACAY7MSC+ntPmDGJ4" +
            "/o6+7M0qU5ag2fxBLlTxHZjRA5UsbuoJ5gQBFop1lHiyeb0o1rKccLNFFP5E/JmDKwfRyVIvnm7CzzDM" +
            "o5AEY64m+E/iSlwPLoBMI4IvuDiSDUqAkfNnv/mdQCwQoD2BfvVSAA8cioH5l5gzilFA50YwXi1sxxRV" +
            "SPXVeTCY44bXgHU8eak+HQbvehSd2I2ZNlfDa6Cbmnm31lUEvUJJgjGDd5aHYfVZA7Gp68DsxG5B3nx0" +
            "PFCQw3h5GmS2EYnMcNmMiNUtGR5QgEDPAExZxJmDBOb8ZXzcZ0PqtHzScrpaMw4dg/gQZa0fdYGpIhhb" +
            "uGoG6c8prxpsN+ai7JKueYDyJNNKG8tECXilpYWYYaia5KwXqjjdswGfNdtT6LbjgE9HcnFBmBgvHU/P" +
            "zCFYRMIuQ7Aa43QaMdcRRaQ/hMbefiVdv+pO7XiCONrLf08ZhGi4QRxNcII4muEAcTXCBOJrgAnE0wQX" +
            "iaIILxNEEF4ijCS4QRxNcII4muEAcTXCBOJrgAnE0wQXiaIILxNEEF4ijCYEQov/59Dm6hBDiFygFmzM" +
            "bcbIOpWgUCHAt24Fw2IQA1wQQLhBHJQTXBAD12Y6DwygUlwXRSD7JdhwcNhFN5FNCKSX+1y3XADos2wF" +
            "xWIJct68JFQmEEApC92U7HA5jELqPEEIFABANeD/b8XDYIulMaqK1wHrpqCxjavZC4rCCIOCYbXVkGtD" +
            "tUYZBFNZkLyQOS3R3JSWQZWXoJASyJzshcZhBIHssK0MnUz92/04U6GoAg2MNJU5/0NblSIqfCGRdFak" +
            "XRSwUCO7uSW84NyEQJEQRC62rIj/peL5pOId1VeSgLGDlwIXGYQFZwErrqsjBn/++x/FAOdWRLYKATf0" +
            "fFocFBAGbcqojW3r87lYb2VZHVsCAZbw6u3sRCBIwYJltdWTFrf6m1wn3gzVSVTyOXQCcmQyOo3vauto" +
            "8N1Vb3el1SKt1VeSgKKKC3+LfRQhkjyiiojd5gDsogboT2miZlIjLr/Me68GJIOCYQRTWdO/n6Q1Va8Y" +
            "Ea6SqeAJPg5I5/Ck+65DrIHSfaMD7d1Li3LS1lkNTSkn4DetD8Rh9AkApKIooUEQICimldi375mQWQoi" +
            "fUjQS4FrXKNR60Ug+Ma8IfkmI+oVD/h+S/BTSLP5cMwAAAABJRU5ErkJggg==")]
        public string ImgVolumeSet {
            get {
                return ((string)(this["ImgVolumeSet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjQzLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0ODo0MC0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0ODo" +
            "0MC0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpmMDVjMWQzYS1hNDc3LTAxNDUtOGM1OS05Zjk3MjllYjdmNTYiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6ZjA1YzFkM2EtYTQ3Ny0wMTQ1LThjNTktOWY5NzI5ZWI3ZjU2IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6ZjA1YzFkM2EtYTQ3Ny0wMTQ1LThjNTktOWY5NzI5ZWI3ZjU2Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDpmMDVjMWQzYS1hNDc3LTAxNDUtOGM1OS05Zjk3MjllYjdmNTYiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6NDMtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz4/ueC3AAAPxElEQVR4nO2da3BUVZ7Af+d2d/phd5JOYiLJBhV01xcwRJZREWE1KxaOqIPywdn" +
            "yvW4VDKALyIctP03NBwTWiQi1ZeGzduaDCioWrrho8RBlKAwqjrorxJFsiIkJHdKh053uvmc/XG4nQJ5" +
            "9u+l7w/l96+77+P9vfjn3nHPPPUdgASmliP8h8MtUUt4JTEJSLaFaCCZIKUNWjq3ILUKIqJS0CjiO4Dj" +
            "Q5PaI7b4nY38WQsisj5vNTrH13vpUmvuRYgHIS7I9ucIOiJ8QcpvbxZuBFYmdY957LBv3Pue/IZ3Sn9V" +
            "1Zo/1RAr7o2nsdbm1p/1P9e4f7T6jEii23jsppYu16PLX2YencAya2OrW5KrAikTTSJuOKFBsvbc+leI" +
            "NIJyT4BROIeJ2s2ik25o23I/d67xL9TQfoOS5EAnraT7oXuddOtxGQ5ZAPWu9f9B1luc+LoXT0DQagqs" +
            "STw7226ACda/zLiXN83mNSuEsXCwrXpnYcPbX5wgUW++t19N8oEtc5ycyhRPQBGnNxR1n14nOECi23js" +
            "pleIgqs6jGJyI282Mga2zMyrRKV2sRcmjGJrwaUcyZEqg3uf8NyT79M/Of0wKp+Ep0m40OxszJVA6pT9" +
            "buJAUTmKgKxqcrjirxxOKUaLrzI6t99bDaYFSae4vbEgKp2E6o0kphfFUXaEYA1IskFIKoSrPimzxFGk" +
            "3aqcHgykUYyaVlHdqwKRCB6JwLJM0JNWFjkLhUCTVmkQJpMgOCdWaEEwodCAKZyIEEzT19oQiW6SUoWF" +
            "HJCoUI6EEUlhCCaSwhBJIYQklkMISSiCFJZRACksogRSWUAIpLKEEUlhCCaSwhBJIYQklkMISSiCFJZR" +
            "ACksogRSWUAIpLOEudACFpiPu4sP2EAeifr7pctPeniYRTUM8hR5LAaAF3OBz4w25qKx0cU1pipmhXm6" +
            "vjFLhSxc4g8Iiutd4s55k2qkc7PDxQnM5jUd0En/tsXQs72VB6q7Q+G1tJzMq4jmK0DlcMALFkoI1Ry9" +
            "my5cayWOnMt8Ln4uyq0JMrUozJRRnerCXGl+KoCdNcZFxabr7BD1JFy1xN4d6/ByO+viqzcWJ76LIeH8" +
            "J5Jl4EQun6aye/DMBzwVxWce/QN0JjWeOVLFjbwIZTQIgwl5mXu/j0ZoTzKroxaNldwmSumBfh5+XW8o" +
            "48HkcGUkYxw95mDfby++uaKPYq+csFzsyrgXa0FTGxo8EsqsPgOLrSlg9pZt7a6K4sl8eYlDSUvB2S4g" +
            "1h4vp/vokAKK0iCW3SZZOOpHTc9mJcSlQc4+Le3ZNoOdb4w9ZfF0J6+o6mVPVe17Ov7vNz8rG8oxIwat" +
            "LeGduK7XB8VfhHncC7WkL8MR7AWQkgajwsfLWFI9fGilILJt/DLPuYzeyI44Ie3nxrhi3VMUKEku+GFc" +
            "CNTSVs2lbCpI65XWl7LilhZCnsHWQaFJj3p4aOhu7wKOxeIGb5ZM6CxpTLhkXHYm6hIcO1bBpSx8kdW6" +
            "oL2ZffXPB5QEIeXT21TdzQ30xJHU2benjoUM16OPk39bxAukS5uyqZf/ObvBoLLvPw2vTW8hxHdkSQsJ" +
            "r01tYdp8HPBr7d3YzZ1ftuJDI8QI98kUN7Qe7EKVFvPRAH0sut2+LZ8nlJ3jpgT5EaRHtB7t45IuaQod" +
            "kGUcL1NBUnil5Nt8d4+bK89PKssLNlb1svjuWKYkamsoLHZIlHCvQnraAUWEGlt3tcoQ8JjdX9rLsbmM" +
            "pkk3bUuxpCxQ4ouxxpEDNPS6eeC+QqTDb+bY1FEsuP5GpWD/xXoDmHmeubeNIge7ZNQEZSVBeV8qrdS2" +
            "FDidrXq1robyuFBlJcM8uZ87z5TiBNjSV0fPtSUSFjx232Ku1NVaExMihwkfPtyfZ0FRW6JDGjKME6k5" +
            "obPzIWB9m5a0pW/TzWCXk0Vl5q1GX2/iRoDvhqD+JswR65kgVsquP4utK8v54ovWUmwca/4ZpW6vzXjI" +
            "8fmmE4utKkF19PHOkKq/nyjWOESiWFOzYawyXWFeXv0cBsT7Bsq+rmftKiM8/Okn8aJSNu/JfwTVz2rE" +
            "3QSw5qtXYbYFjBFpz9GJkNEnxdSV5eaouBTQcLafujxXs+K8o9Kb6f+vM/0jDOVW9RikUTbLm6MV5P1+" +
            "ucIxAW740Ql09pTvnx97eGmTaGxPYtLUP2VG4YalmbmauTsARkR7s8JE8dgoR9nJvTTRnxz0c8XLTf9f" +
            "yr/8phh0bPXVuSc7OORz31kQRYS/JY6c42OE7L+e0iiMEeqHZ6O6feb0vJyMJW0+5uedALfe9VETnF13" +
            "Dbjt1bglv/v3/AcZt7lf7J7Lph7FXqjf9UMav9k9EDlO9cQnJzOsNccyc7Y4jBGo8YjTXH62x1uM8sIL" +
            "87e4uGMHFs+WZ/2kt3++N0LAlOSaJNv1QRsOWJN/vjXDnp7XDSmTmaOZsd2wvUEfcReKvPQifi1kV2Ve" +
            "eh6ogD8VAeQDu+mwiTZ90GR8ko5bIlMeU9egnXdz12cQht59V0YvwGTl3xO3/eMP2An3YbqzEUHZVKOu" +
            "3J4AxV5Bnhs/cdn5Vz4A1rhmVRGfLA4A4fawh8GiS8N8Fgf7c7YztBToQ9QMwtWr0A9KTumDzj2Gmv5v" +
            "9eJvNbyfO6EBcfPkJli/0jFqioeRZvtDD4hEe/k67xLh9mbnbGdsL9E2X8fb1lNDIpUfbKTfLvq5myqs" +
            "VrH0jRex/rTX5X9iaZPOP4czn0UpkRR7oz9XM3c7YPsL2dqPkmR4cvv7z++8reX17ApK5a+YjYe1baYr" +
            "uL+XBiV2AIRELzxLktEQsNCSyIg+YubozudsZ25dAiahxEWt8w1d8X99hDKjPObrk92+dedzhSiKr8kB" +
            "/rmbudsb2AhE3LmbQM8LF7M3jxU6fW3kfSiKr8sCAXOMjtxYLje0FMqdYMSc6sBODSmSSpTzQn6uZu52" +
            "xvUAKe2N7gbSAUc/v7rPfEIdBW1smY+hsPBszVzN3O2N7gfAZF7EnOUKvrP/89toO1VQfa2fjYGRy9Sm" +
            "BLOMNGRezJT78xXxwXhF48pPOjfXFZ3werp9nLJ2NQ2HmauZuZ2wvUGWlcREP9QzfK/tvV7az559Pccf" +
            "8IKI8d0Mh5txezKvT+9/8GKmTcKw91oNh5mrmbmdsL9A1pUZL5HB0ZCmqLkrRcG0rhx/uYNUiN4G/LR5" +
            "xn+H4h3khXpw2enlMrEpk5mrmbmdsL9DMkNED/VXb6P8bPZrk8UsjHLo7+3fG5s0P8h9Tj2c+j/XxhBW" +
            "JvvzJ+LOYudsZ2wt0e6XxaOLEd1GSevYtscW/LkJUjP7WdvaZ3m8LjrmTcCiJ3m8LDrlPUhdE/sd4Wm/" +
            "mbmdsL1CFL433siAynmZfR/ZPp5dP7qTxNx3cMT8I/pFbNx+838Pyv/S/LfrejceYfHOp8WEMnYRnSzT" +
            "55lLeu/HYkNvv6/Aj40bOTpiD2vYCAdRdYYT5cou197MCRZKGa1vZ9UiUq+eUDt6DPICBEgkJ229q5sr" +
            "Z4TH3MJsSXTk7zPabmod9m9bM0czZ7jhiiruDHT5+84oHEfbyl8c6czbD6uGIl385WDniuOg75gdpuLY" +
            "1J+ccjrQUXPtSOTKS4I+PJB0xcbkjNJ9REccz8SJkJMHbLbkbpTclnODTf2zm3/9J4r1s6HrJB+9bm81" +
            "+tLzdEkJGEngmXuQIecAhAgEsnGYMqVhz2FrTfDDunNDDl4tax1zRzjVmbmauTsAxAq2e/DMi5KH765P" +
            "sbsv9UE8hh65o57Jjcih2t/np/vokIuRh9eSf836+XOEYgQIeybzZXgBWNubvnamBFe3rbyvBNznE0rn" +
            "5bw2ZOc2b7XXUOhuOqESbdCc0Zr4eRnb1sWqRu2ATiOeazT+GWftGClFaxIEHI45aX8MxJRBAsVdnyW2" +
            "G7+s+dhNNOir8QYkmNdZ9bNwul9wmHSUPOEwggKWTThC8ugTZEWfenpph3/K0O1Jg5NARJ3h1iSMXZXG" +
            "cQADvzG1FhL10NnbxcKNz51p+uNFYAkGEvbwzN//9TPnAkQLVBtO8eFf/XMsbsxj1V2g2/lCWmeP6xbt" +
            "ijl3Jx5ECAdxSFWPxAqPu8Py7aT5pt/9bnCaftPt5/l1DmMUL3I5ewcexAgEsn9SZmWv58XcDjpDok3Y" +
            "/j7/bP8e101fucbRAAK/8ooXKGaXIrj4e+1ORrW9nG38o47E/FSG7+qicUcorv3DuHNcmjhdIE7B7bv9" +
            "ySs+/leShQ/ZqnUlhLEf1/FvJTMmze24zmo1izBbHCwSGRK9Nb2HxwqJMxXrWzlpb9BNFkxqzdvYvR7V" +
            "4YRGvTW8ZF/KAw3qiR4Na8vL8Mu4EArXo7vlkXApkopb9zj/jWiAwHsA+c6SKHXsTyGgSABH2MvN6H4/" +
            "WnGBWRW/WU+cldcG+Dj8vt5Rx4PM4MmLMpC9CHubN9vK7K9oc92xrrIx7gUxiScGaoxez5UuN5LFTme+" +
            "Fz0XZVSGmVqWZEoozPdhLjS9F0JPOzJLR3SfoSbpoibs51OPncNTHV20uTnwXRcb7b0ueiRexcJrO6sk" +
            "/O2pIhhUuGIEGcrDDxwvN5TQe0YedYHw0eC8LUneFxm9rOx0zDDWXXJACDaQj7uLD9hAHon6+6TKmlUt" +
            "E0xBPZebn0QJu8LnxhlxUVrq4pjTFzFAvt1dGHfHqTT654AVSWKPwPW0KR6MEUlhCCaSwhBJIYQklkMI" +
            "SSiCFJZRACksogRSWUAIpLKEEUlhCCaSwhBJIYQklkMISSiCFJZRACksogRSWUAIpLKEJIew/n77Clgg" +
            "hopqUOHNmI0XBkZJWTcDxkTdVKM5FwHENoQRSZInguAY0FToOhUORHNXcHrG90HEonIm7SLwvpJQi+qz" +
            "/OMhLCh2QwkmIn0JP91ZrQgiJkNsKHY7CYQi5TQghNQC3izcLHY/CWZjOZCZa61nr3aPrzC5cSAqnoGn" +
            "sDa5K3AIDHmW43NrThQtJ4SQGupIRyP9U7340sbUwISkcgya2+p/q3Z/5OPA3tyZXAeNjDSVFPoicdiT" +
            "DGQIFViSa3G4WaYILe9IbxTlogrTbzaLAisQZHc/nDOcIrEjs1DWeOn+hKZyArvFUYEVi59nfDzoeqHh" +
            "lYoOm0ZD/sBROQNNoKF6Z2DDob0PtFFyVeBIXy9Tt7MJFE6RxsSy4KvHkUNuMOOF+bL23PpXiDSCcy+A" +
            "Utidyus5zzm1rICMOaQ2sSOx0u5mhmvgXEJrY6nYzYyR5YBQl0EB6n/PfkE7pz6oe6/GJprHX5daeHtj" +
            "PMxJZrRkTW++tT6W5HykWqKf4Tkf8hJDb3C7eHE2Jc87eVk4tpRTxPwR+mUrKO4FJSKolVAvBBCllyMq" +
            "xFblFCBGVklYBx0+PQm1ye8R235OxPwuR/cIh/w8m2EOd1GQ7XgAAAABJRU5ErkJggg==")]
        public string ImgVolumeMute {
            get {
                return ((string)(this["ImgVolumeMute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjQzLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0OTo1MC0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0OTo" +
            "1MC0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpmMGZhYTJjYS1jMzJkLTI3NDItOWNhMC0wNzFkYzJkMGYzMjYiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6ZjBmYWEyY2EtYzMyZC0yNzQyLTljYTAtMDcxZGMyZDBmMzI2IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6ZjBmYWEyY2EtYzMyZC0yNzQyLTljYTAtMDcxZGMyZDBmMzI2Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDpmMGZhYTJjYS1jMzJkLTI3NDItOWNhMC0wNzFkYzJkMGYzMjYiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6NDMtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz5/jDcQAAAOv0lEQVR4nO2da3BUVZ7Af+d2d/pBOnRISIRMVDJUKRaIBJbB4SElLKxjiTqoH2Z" +
            "212fxAQShePhl/WTVVvEqBcTaonzO7MxOqShgOYoFFvIYGBbCIJa6VRCFVAOJCQnp2I909z374dJN5J2" +
            "+ndx7wvl9Srrv4/+/99fnnnvuuecIbCClFMlXQ7/KpOWDQB2S4RKGC8EwKWXYzrY1xUUIEZOSMwJOIzg" +
            "NNHp94pPA4vjfhRCy4O0WslJ8rX9mJsvjSDEH5C2F7lzjBsRZhNzm9fB+aGlqR6/X7s3CiVeCk7IZc5V" +
            "pMrW3O9K4H8Ngj8drrAguSRy40XVuSKD4Wn9dxhSrMeVvCw9PowyG+NBryOWhpanG6y16XYHia/0zMxn" +
            "eA8qLEpxGFdq9Xp643mXNuNaXnWv8C80sn6HluRkpN7N81rnGv/BaC121BOpa7X/VNHmh+HFpVMMwWFe" +
            "6PLX4St9dUaDONf6FZFnfp1Fp1MLDorJlqQ2XfnyZQPG1/plmls9Miad/ItOogCHIGh7+5dI60c8Eiq/" +
            "112UyHELXeTRXpt3rZULPu7OfVaIzpliNlkdzdcovOJInXwIlXglOSneb+/s/Jo1q+EqMe3ONjfkSKJs" +
            "xVzkXkkYlerpiwIWKs348oblBTJOp8bX+mXBBoEyWx50NSaMaOWcMKaWwnqprNL1AijlSSiF05VlTKL4" +
            "S417jQmcwjabXZNLyQQOoczoQjbLUGUiGOx2FRlEkww2JFkhTGBKGG0IwzOlANGoiBMMM/faEplCklOF" +
            "r9kjUaK6HFkhjCy2QxhZaII0ttEAaW2iBNLbQAmlsoQXS2EILpLGFFkhjCy2QxhZaII0ttEAaW2iBNLb" +
            "QAmlsoQXS2EILpLGF1+kAnKY16eHzljAHY0G+6fDS0pIlFctCMoMZzwBghLwQ8OIPe6iq8nBXJMPEcIJ" +
            "ZVTEqA1mHM3AW0bnSX/Ag06pyqDXAa00VNBw3Sf3QZWtb/ttLqR9p8HxtGxMqk0WKUB1uGoHiacHKE0P" +
            "ZfNQgfeqn/Oci4GHInWHurs4yJpxkXGmCmkCGUl+WshLr0HR2C7rSHqJJL0e6ghyLBfiq2cO572LI5MU" +
            "SyHfrIOaONXnxlz8S8t0Uh3XgC9SZMnjpeDXb96SQsTQAotzPxPEBnqk5x+TKBD6jsEOQNgX7WoO8FR3" +
            "CwcNJZHvK2n7Yx+ypfl4e2UyZ3yxaLm5kQAu0oXEIG3cKZEc3AGWjB/PimE4erYnhKXx6iCuSlYKPomF" +
            "WHiuj8+vzAIhICQtmSBbWnSvqvtzEgBSoqcvDI7uG0fWtdSLLRg9mTX0b91Un+mX/XzYHWdZQkRepdNR" +
            "gtkw/Q23pwKtwDziBdjeHmPdxCNmeQlQGWHZ/hudua3ckljdOlrPmCy+yNYko97PpoTjTquOOxNJXDCi" +
            "B1jVW8Pq2DKRNKuojbJ8WJexztg4SSxvM3l1DW0MH+Azmz/HyQl2bozEVkwHRkGhKePJIDa9v7oa0yaS" +
            "ZZeyb2eS4PABhn8m+mU1MmlkGaZPXN3fz5JEazAHys1VeIFPCfbtqObCjE3wGix7z8e64KEWuI9tCSHh" +
            "3XJRFj/nAZ3BgRyf37aodEBIpL9DT/6ih5VAHIlLCm7/rZsEI997xLBhxjjd/142IlNByqIOn/1HjdEi" +
            "2UVqgdY0V+ZLnjYfjTKnqn7ssO0ypSvDGw/F8SbSuscLpkGyhrEC7m0NWhRlY9LBHCXlyTKlKsOhhayq" +
            "S17dl2N0ccjiiwlFSoKYuD/M+DuUrzG6+bF2NBSPO5SvW8z4O0dSl5tw2Sgr0yK5hyPYUFfUR3qmPOh1" +
            "OwbxTH6WiPoJsT/HILjXH+VJOoA2NQ+j69jyiMsD2ae662+otQmLlUBmg69vzbGgc4nRIvUYpgTpTBht" +
            "3WvPDLLs/44p2HruEfSbL7rfqcht3CjpTSp0StQR66Xg1sqObstGDHXs80Rc8d1s7ZaMHIzu6eel4tdP" +
            "h9AplBIqnBdv3WN0l1tRf+1GAvKHJzN1FLqfte1LE0+okoIxAK08MRcbSlI0efM2n6g/sr2XU+gj/2vA" +
            "L4t3qnIj7qhNWKRRLs/LEUKfDuWGUEWjzUSvUF8d0XnO5xr0dyGSW/915nvF/GcrW02VFjWPyzlruWB3" +
            "mjtVhpnxRW9Tlc7nlclUBJSI91BogfeonRLmfR2tiN7ye2ZxgxZ8ks/bV0posTjtLa0NH/u8fD3dcdbl" +
            "Cln+0JoYo95M+9ROHWgOFBdjPKCHQa01Wc//E8YGCehKe/FsHU/8QYeP37r5N9gjJxPGWOLmc3Y4SAjU" +
            "ct27Xn6kpvMXZPN/N+g/STPq8lu9jJcUKrejkcszl7HZcL1Br0kPqhy5EwMPkSvvPu9qPdvDA2yH+47t" +
            "qV3anmFyZQASsnIt12e1LXC/Q5y3WTAxD7gwX/PbEpchUlvc/jjNuy3AOtQWLss1i4TMk5XeUAhdzdzO" +
            "uF+hgzDrBd1cXv0N68niM37/j46kjNSQyRd98wYy9xbp85XJ3M64X6JsO6+3rMeE+euvTlOzf0cn4/6n" +
            "mr2cH9c0+ekku11zubsb1ArW0WCXPuNK+7e+TPRtnyR8NfrO/lraks4cll2sudzfjeoFSMesg1gT65xp" +
            "zYm8Hk/9Yzhsny/tlf1cil2sudzfjeoFIWgez1Nd/B1N2dLP6vQy/3lHLyZiv3/abI59r0kUVs6vgeoF" +
            "yQ6zkBjroT9qOdPDAlv5vfMzlmsvdzbheIKcxfOo8kHUC1wtkhKw7kU4HnqxX3BPhkwf7/y3SXK653N2" +
            "M+yMMeOF8N11pDxWB/mneNwaXsOSfJfNGNPXL/i6lK32hBTrg/tPj+gj9YQ+JZogmvdwWTvf5/uqmRPj" +
            "vcdF+k/VKRJPWafGH9aMM21RVWQfxSFfftsp6bgnxyr+ZfHpvk6PywMVcc7m7GdeXQHdFMpwEjsX6qH+" +
            "MIZh0f5j/GhMl6JKjYeWa5q6I++/CXHLIrs7EcIJPga+ai/9rDIwM8+a0diZUuOvdsqNnrQvDxLD737Z" +
            "1/SVsVpXVA/HcdzHSZnHuxITfw9yHBtHwyBkmVLjrJKVNQfv/WSPH5nJ3M64XqDKQxX97KTKZZV+r/Xp" +
            "Q+dgInz4d5z/vPFv0cRKLwb7WIDJp5azCGNSuFwigfqQV5lvRwluFRZmPRY/5ODCriRHh7mKFVnRyOeZ" +
            "ydjuurwMBPF/bxn58HDycJHuP6HXJcfvkcv5UH3X9LzorBQcPW105nq9VYxg8JTSfUJnEd+sgZHuKj6L" +
            "X6aXXo5pkVAdZ9XvB9l+fKpo8lfWR/N9Dx0euulwhy38UDSPbU/huHaTMqPdKlEAAc8ea/OUUrDxWxmO" +
            "/uPq7YaOmRfj2b53807Qwm0ZHCRX5Iey+GU0wI/ff9Su5vVl+5bEy4Dxzx6rRoR4UGqU1nhbUv1mOjKX" +
            "Z9O+Za76dmpW9v8w5zZfNQeb9wYsI+2h4tl2ZqRKUuIQBhHyS2VP9ACxruPY7U6rJAxdzmj3Vr4w8oJB" +
            "AAC+PbEZESuj8+ryjPQaLzRsny+n8+jwiUsLLI5udDqdXKCVQmd9kwQzr17nmCy+xtFLhX5FY2mDNF1Z" +
            "VdMEMqdzkLMqdgYV15ygdNRjZmmT27holh3LJIQVWDq1JSkcNVnJSFuUEAtgy/Qyi3E9bQwdPNag71vJ" +
            "TDdYUCKLcz5bpZ5wOpyCUFKi2NMumhy6Otez2QROuxMbvh+THuN70UFzZmXyUFAhgWnWc+XOsusP6rVn" +
            "2trj/Lc4ce1uCrN9qCTN/jlfpGXyUFQjghbq2/FjLz20NKSHR3pYgz229OMa16jP3KC0QwNv3RKmaEEF" +
            "2dPPsn0tcfTnb+P0Qnv1zCbKjm6oJEd6+x139kApBeYEMAV9Ovzid0voP0jx5xF13Z1JY01Gt/yCdL3m" +
            "+nN6E4aIYC0V5gcCS6N1xUebPLclXrCfvqHVFO1EsbTB5x8XpqObPLeHdcdEBIQ8o9CzsRtFTXvYvA04" +
            "g0JPu9icDUqAcetrvvmdACwTW/BovHa9m+54UMma9mCjK/UwcH+CZmnNMrkwUPHRe2hTsaw3yVnQIBw8" +
            "nke3WSPoi7GP2VD8vj2xW7tlWbxnwAuWIpwUrTwxl81GD9Kmf8p+LgIchd4a5uzrLmHCScaUJagIZSn3" +
            "Z/CgZnd2CrrSHaNLLka4gx2IBvmr2cO67GDJ58bLku3UQc8eavPjLH5XqkmGHm0agnhxqDfBaUwUNx01" +
            "SP3TZ2pb/9lLqRxo8X9umTDfUYnJTCtST1qSHz1vCHIwF+abDS0tL1hoZLJnJj89jhLwQ8OIPe6iq8nB" +
            "XJMPEcIJZVTHXd9Tva256gTT2cL6lTaM0WiCNLbRAGltogTS20AJpbKEF0thCC6SxhRZIYwstkMYWWiC" +
            "NLbRAGltogTS20AJpbKEF0thCC6SxhRZIYwstkMYWhhDC/ePpa1yJECJmSImaIxtpHEdKzhgCTjsdiEZ" +
            "NBJw2EFogTYEIThtAo9NxaBRFcsLw+sQnTsehURNvifirkFKK2KrgaZC3OB2QRiXE2fCKxHBDCCERcpv" +
            "T4WgUQ8htQghpAHg9vO90PBq1yDmTH2ita7V/t2ky1bmQNKpgGOwpXZ6aBj0eZXi8xgrnQtKoRE9X8gI" +
            "FlyQOYIgPnQlJowyG+DC4JHEg/2/P77yGXA44MyKlRgXaLziS52cChZamGr1enjAEN/egN5rLMARZr5c" +
            "nQktTP2t4vqw7R2hpaodpsKT/QtOogGmwJLQ0tePSz6/YH6hsWWqDYbCu78PSqIBhsK5sWWrDFb+72kq" +
            "ly1OL8bBIX85uXgxBFg+LSpenFl9tmesOuB9f65+ZyfAeMHAmKdXcCO0X6jyXXbZ6ct0uraGlqR1eLxP" +
            "0Lf5NhCE+9HqZcD154AZKoJ4kXglOymbMVbrFemBiGOzxeI0VPdt5rkdBc8bE1/pnZrI8jhRz9FN81RF" +
            "nEXKb18P7N1LiXLa2nV1LKUXy1dCvMmn5IFCHZLiE4UIwTEoZtrNtTXERQsSk5IyA0xd6oTZ6feKTwOL" +
            "434UofOKQ/wf4g1PGdCH+QwAAAABJRU5ErkJggg==")]
        public string ImgPlayPause {
            get {
                return ((string)(this["ImgPlayPause"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjQzLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0OToxMC0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0OTo" +
            "xMC0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDowZDdhYzFlNS1kMjQzLWY0NDgtYmZiNy05NTY0Yjg2MTE4NzkiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6MGQ3YWMxZTUtZDI0My1mNDQ4LWJmYjctOTU2NGI4NjExODc5IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6MGQ3YWMxZTUtZDI0My1mNDQ4LWJmYjctOTU2NGI4NjExODc5Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDowZDdhYzFlNS1kMjQzLWY0NDgtYmZiNy05NTY0Yjg2MTE4NzkiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6NDMtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz6yqSR7AAALSklEQVR4nO3de3BU1R0H8O85e3dvdvNYQsAk2wQ11aKT0VYmEpBJfSUgIAEVQkc" +
            "r03H6R+2MPCYG+5ixrbV1JGYAHW3/cKy1OsNrAIOkgKFWqQgVy1Sr2FpTJW8J5MXucpO79/QPkpib3WQ" +
            "fJ5vN3f19Zvgjd/fe/e3Ol3PPvefcexkkCCHYpW2uUn1QLAdQBAGPADyMIV8IkSmzbTK5GGP9QqCdAW1" +
            "gaAPQpNjZwbSNvpOMMRHzdmNZyVenlusBrIFglYDIi/XDyXTAOsBEvWLDble11hj12tG82b/VuSCgG1s" +
            "MA2XRfhCZ/jjHMZvCNzs3+U9Euk5EAfLVqUW6wWphiHtjL49YBmd7FS5qXNVaU7i3hg2Qr04t13XsApA" +
            "9KcURq+hWFFSF263xiV7se0Z9xAjgECg8qSjbCOBQ3zPqIxO9adwW6GKtus0wsGHy6yJWwzm2Z9RoG0O" +
            "9FjJAfc+ojyCAZ+NaFbEWG9ZnPao9N3ZxUIB8dWq5EcAhQ8A2NZURK+AMAW7DXWP7RKYA+erUIl3HKVC" +
            "fh4TWrSgoGX10ZupE6warBYWHjC97KCMjRlog/1bngsEB472pr4lYjd3BFw6fbBxpgQK6sSVxJRErGZ0" +
            "VDgx1nGl4gkTIMFDmq1PLgaEA6QGsSWxJxGqGM8OFEOzyqDohURCsUgjBGHWeSazsDr6QD00GIyRq+qB" +
            "YzgEUJboQYllFHAKeRFdBLErAwwUoQCQ2AvBwxpCf6EKINTGGfE5XT5BYCSEyJ5yRSEg4FCAihQJEpFC" +
            "AiBQKEJFCASJSKEBECgWISKEAESkUICKFAkSkUICIFAoQkUIBIlIoQEQKBYhIoQARKRQgIoUCRKRQgIg" +
            "UChCRQgEiUihARAoFiEihABEpFCAihQJEpFCAiBQKEJFCAYqD29+Zg+aLqfGoEQpQHLT9oxflL2fhF59" +
            "eASPmx9laAwUoXvw6dhzwY95+D051pSW6mrihAMWZ/7/9eOCPDqw7XYCLA8n3cyuJLkDWR91q0DKFAfn" +
            "OAcxQ47v/MATQ6rWhZ3DMzyhE0BtPNvZi/j9z8OvFl3Cfpz+udU0l1vd0nH/lOJtbO/4d+lzfysKT83u" +
            "xPP/ipH7mv3vsqP40H5990A/49KjX95RmY8fNrch1Bia1rkRI6gANW1iehT/MawWT/KaCARs+8uBwoxc" +
            "YNOQ25lLwwyU21FzTJbedBEu+nXII7zX2YfGxOdBF2Kecj6tP41h0pBCH/9wvHx4A6hVpWOT2Sm8n0Sz" +
            "fB4IjxPmWgAEEzM3N2fe6sRSFOFJ2NuqW6JxfwZ0Ns6E19URWw8D4uyam2rCyQsVvr+uATbZJnAYsvws" +
            "LRdOBDZ948Nbh4M5q8a1u7J3fEvG2Or0K7qzPwWCLz/yCnWNphQu/uqYTbtXcIs3d5g7ZSuV8ZwZeW9C" +
            "JqzMHIv786S4pd2GqAvz+xjY8VqUAdvNX/PjtXtScyYtoOz0aQ0XD7KDw8BwVrz04gG3F7UHhCYVlq3h" +
            "srYLjFc1JFR4gSQM07KEru/Gb1SIoRPVvePHilxM/W9g3wHD7IQ+0L8xHcPYCF45UdaMkxx9RDdffOgM" +
            "nH7yAh+Z0R1e8RSR1gABgdUEfnlgNgJs70LX7DBw/5wy5jiGAxX8rgO8/fabl9gIXjlaeR2FG+MNve2E" +
            "6frfOwP75zRG1UlaV9AECgLUFvfjxPXbzwkEDD9Wnhxz0rDpVgHMf9JiW2fJcOLqqC7np4c/7VC5x4nR" +
            "VJ+7Itf5RVjgpESAA2FB0HnctyzAtExc03P+++WFFj3+ai4/+2mtaxmaqeL3yQsQn/mqv74CdJ92xSUg" +
            "pEyAA2F7cjqsWfd33YWk2PHvDVyN/72vNws43xhxtORW8usqLa92DU1WmpaRUgADgQGkznNdePnv9s5X" +
            "ATbM0AMAnPWn4yX4bMLrh4AxPrQpE3GFORSkXIIdN4NDiTnxvhRPr5vQAuHy4vuYNd9C41rqVabi3oC/" +
            "EVsiwpDyRGA1DAAuPFKDnQ3O/58bb3Nh9c+QnHFNVyrVAY607HRwe9w1u7ChpTVBF1pLSAXq+aSbeP2o" +
            "Oj5LvwpHbW5NinGoqpGyATnQ58Wz9mMNyl4Idy3viPhEtmaRkgDr9NvzgQEbQgOcTKw3ckH35qOx0l4q" +
            "6z2clojxLsf50jigNBBiWHM6F6DKP1C9bloG1Be0AgPOXOO5vcMM4dwlXr82iI7EJpFwLtOJkIfyfmcP" +
            "jKc3G1uLL4QkIhrve8sDo9AOGwE9ft+HU+dBjZiTFArT+43x88a55VDztm5k4uKB55O/97Rno+9eojrV" +
            "Px/f3paOpb8xYGgGQQgHa3pSDww3mqRlspoqDSzrhcnzdab7P048bb3Ob3ie6Nayon4kOX2RXm9acycO" +
            "gEfv0WStJiQDtbHHjhX1jxrIcNrxU6UVBevAA6c6SFuTMm2Faprf7UF4/G1/5w3cb6w/7cdOuXPylM12" +
            "mbEtI+gDtacnC43uAsdcYP3YPwy2zQ49xcQY0lrUgfa75io/BZi/ueH0WWrzhW6LBZi8efoVj1d8L0as" +
            "l78+cvN8MwEtfZuPne1jQ4Xrl3elhZwi6HAJvLu6AfY65FRls9qJiZ3bElyufebsHpX+aiZfOTjwD0qq" +
            "SMkCaDvzoQw+e3qUHhaf4Vjdqr++IaDs5aQaO3t0Fe6E5RMZ5DQ+8qmLjx/noi6B1Ed0ant6p45Y3C/G" +
            "/fkfkX8QCLD+YOnf7jOCFIS7rAYCrFmXj0KLoL+vp9CqoaJgdND96RJSX9dyzOA1Pzu1MiuES67dAA4H" +
            "gfyHCU7gwGw0Lm2O6OjU3XcfxlZ3I/vaMyGqYgNAC2HvAi5v25I07J9tKrB+gCCwoz8KbZWel/sdnOAw" +
            "cr2jG0mUZgE3+EF376hLe7bX+UVpSD2WkX5eFp27uxZK8VvNMwxhxBmwrbsfD37Bj05k8fP5BP+CP/gY" +
            "JdHOFaSTU7V0czECeMxD3y2l0wdB6UUGfbm7IV7+sAnrwz2qbnZZ0t3exfAs0PHqeCAoTuDIzxGR7lgZ" +
            "Tk8cZSu/IwgvFbchwJNc1YpYP0HTnvCYTL5ZdQMms5JweSwGKF6eCteUO/HJu29iLYpMKBSgOPPPceGV" +
            "ea0SXQFud5TvRJLFS4jwQiR8KEJFCASJSKEBECgWISKEAESkUICKFAkSkUICIFAoQkUIBIlIoQEQKBYh" +
            "IoQARKRQgIoUCRKRQgIgUChCRQgEiUihARAoFiEihABEpFCAihQJEpFCAiBQKEJFCASJSKEBECgWISOG" +
            "MseS53xqZUoyxfi4E2hNdCLEmIdDOGdCW6EKINTGgjYNRgEiMGNo4gKZE10EsSuBzrtjZwUTXQaxJcbA" +
            "GJoRg/VucbYDIS3RBxEpYR+Zmv4czxgSYqE90OcRimKhnjAkOAIoNuxNdD7GW4cyM3AL7Yq36jmGgLHE" +
            "lEavgHMcyarTvAqOGMmwK35y4koiVjM7KSICcm/wnwNnexJRELIOzvc5N/hMjf45+TeGiBsDET6Mlqax" +
            "7KCMjTAFyVWtNioIqzpD8D3kgUeEMAUVBlataM514DprO4arWGg2OTVNXGrECg2OTq1prHLs85HygrEe" +
            "15zjH9viXRayAc2zPelR7LuRr462UUaNthA3raXeWujhDADasz6jRNo73nrCPQvPVqeW6jl0AsiezODL" +
            "tdQ/1eYJ2W6OFndLqqtYaFQUldIifQjjbqygoCRceIIIWaDT/VueCgG5soTPWyYlzHLMpfPPo8zzhxPQ" +
            "0T1+dWq4HsAaCVdIovtWxDjBRr9iwO5IWJ2htmY8WQrBL21yl+qBYDqAIAh4BeBhDvhAiU2bbZHIxxvq" +
            "FQDsD2oZmoTYpdnYwbaPvJGMs5see/h+nyoFV/RaLfQAAAABJRU5ErkJggg==")]
        public string ImgShuffleOn {
            get {
                return ((string)(this["ImgShuffleOn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjMxLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0OTowMy0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0OTo" +
            "wMy0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo1N2UzN2U5Yy04NjdhLTBiNGYtYjlhMy1lNDVlYjdhMzQyMDQiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6NTdlMzdlOWMtODY3YS0wYjRmLWI5YTMtZTQ1ZWI3YTM0MjA0IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6NTdlMzdlOWMtODY3YS0wYjRmLWI5YTMtZTQ1ZWI3YTM0MjA0Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDo1N2UzN2U5Yy04NjdhLTBiNGYtYjlhMy1lNDVlYjdhMzQyMDQiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6MzEtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz5BJrc7AAAPnUlEQVR4nO2dbXMcVXbHf/d29/TM6NGSkJEKbOMirmTLBm+Vt4A1hId1NmxIUal" +
            "Uwbt8BAiUMd8hgAsIHyEvUrVU8YIKC9k4wAIuoCBZWJutikOMH1jJljUja0aa6Z5+uHnRakljy5Y0Pdb" +
            "0le/v3Tx0zznT/z739r3nnivIgFJKeG+UHwgD9RSwF8WkgkkhmFBKDWQ5t6G7CCHqSjEtYArBFHDWdsR" +
            "7xRcaXwohVMfn7eSgxnH3SBjxDEo8DerOTn/ckAfEJYR617Z4u3zUP7Hpozfz5ebrpQejMH4ljnlksz9" +
            "kyD9S8qlly5dLLza/2OgxGxJQ47i7N4zFq8Tq7zs3z6ANUrxjS3WsfNQ/u95X1xVQ47h7JAz5NbCjK8Y" +
            "ZdGHOtnl2vWZN3uzD2mvuc3HEBxjx3I7siCM+qL3mPnezL90wAi286r4Rx/xj9+0y6IaUvNl/zH9hrc/" +
            "WFFDtNfc5Iv75llpl0AuL5wdf8t+69u3rBNQ47h6JIz6IFdbWWGbQASmIpMWT1/aJ2gTUOO7uDUO+xvR" +
            "5DGszZ9scWv101taJDmPxKkY8hhuzY0kjyyxHoObrpQeDVvz51ttk0A2nIB9KBxuXI1AUxq/0ziSDTqz" +
            "WioSljrOZnjBskDjmkcZx9wgsCSiMeKa3Jhl0I9WMVEqJZFbdYNgESjytlBLCdJ4NneIU5ENyKRnMYNg" +
            "0YaCeksDeXhti0Ja9EsVkr60waIpiUiqMgAydoWBSCsFErw0x6IkQTEizesLQKUqpgZtmJBoM62EEZMi" +
            "EEZAhE0ZAhkwYARkyYQRkyIQRkCETRkCGTBgBGTJhBGTIhBGQIRNGQIZMGAEZMmEEZMiEEZAhE0ZAhkw" +
            "YARkyYffagF4TxFBpSqq+oBZazEcSL4ZACVpx8p2CBEcoihKGrJhBO2LEVYyWYpzb/Ba8LQVU8wTnFi1" +
            "+9G0qwfoKaEbQRFADZpCADfXks1En5i43ZE9fxGCx43rd2nLbCChSgh/mBWcaDpVgpfiaI2CiGDJmRfQ" +
            "XFEN2jGuBbYMl0mMhDMGPYD6ULLQEs5HFtJcIsBIU+HYBRp2IfeWAe4YUVufF37VC1P7J3daehrHgzFX" +
            "J6YaLHyXvlSy4t9xiV1/EcEEhO6rXD7GCqy3BhUWL7xsFmkvndy3YX/bZNxxjy239925vAZ2vSb6quTS" +
            "jRCGTbsT+wYDxvphuBwglYGZRcrrmMOUnEa5kKX426LN7MO7uj+WIbSmgZgtOzhWY9pIWetKN+Olwi5E" +
            "t6qNUPcHvrxaWhTRRDDm8o0WpsCU/v6VsOwFVPMlHs0WaEfRbEYeGWtw90BsXL9YFX88XWIgsShY8PuY" +
            "xWtxe0WhbCeh8XXJyziVSgl2lkMNjQc/7IGEsODnrcKFpYwnF4R0+uwe2j4i2xSiGUvCHis0n1SKREhw" +
            "YaPHoeKvn4gGwpeLR8RYHBlpESvBJtcgfKjaq96Z1Be0f45WCz2ZcznkWUigezukdfnAkZIcT89mcy7c" +
            "LBeZDi4fHfUSHT4B5QfsIdKpqc86zKFmKX+30cimelN0DMb/a6VGyFOc8i1NV7e9fvQV0vi75dqGAFIo" +
            "n7vAY0aA7N+Imtkqh+HahwPm61pdAXwFVvKTDDPDwDl8L8aSMuElTC3ByzqXiaXsZ9BRQswUfza50mPP" +
            "cbN2I3QPxcsf6o9kizVavLeoMLQV0ci6ZNthVCjk4EvbanI45OBKyqxTSjBKfdEQ7AZ2vSaY9m34r4vB" +
            "Y0GtzMnN4LKDfipj2bM7XtLscegkojAVf1ZJ+z6GhfIzzpHw5axOpzT+T21JxaChpv76quYSxXs/1Wgn" +
            "ozFVJMxJMulHPpiduxJnFAu9NudS8zQvg7gHFpBvRjJLMAZ3QxtpICU43kujz0+F89jjnQ8m/zRT53w6" +
            "aotSn0w23o0jWK7QR0A/zAj9KZta3ala9EyIl+GKuyO9mCgSbeDgcKSZRyI8SX3VBm6HQMw0HgP2DG+s" +
            "4/8v58nXvpYlkB4YDrE6zyJZYaMH5usXFwKa2RlrshaZNZUryyJjPHRsU/P7BgKkrFmcaDvcO+5ns2yq" +
            "0EFDNE1QCiz6pGO+LocMA1IzgVL3Anzybh0c9htzNnyOKBafmLL5bdIjXaWoWI8kHl0scHPDZPxqtm8Q" +
            "23hdTqkIlsKh5Qoscay2asHOLSWLW3r6gK5mE1UDy/uUyM43NRaG6r/jgksuphcK64ukEoZIICSs+5x0" +
            "tBPSjnwTKXX1R184ZKDgxW+TS4saEUPEkv5kpU93AKo6UPivmyZ1NDoysH31SUh9Tn/NO7q0MYqgEEkf" +
            "AcGHj4ecfdjfaXtcDwR/nLc4sroz4RkrwYaXIEeExXr7xuau+4MQVl9aqMRpLKH7SF7CnHNLvCv71Yqn" +
            "tmF2lkJ+PtnA2GUiGCwpHJD4HMblfd5Zz85JFf5DkFWfp9w44igfGQh4babYtuUlEVOJqc+3jrjbhP64" +
            "U28Qz6sT83USTg6MhwyXaBjQtoXhwh8ej45sXD4AUMFFIolDqe57JvYVVP7lwY1Z3mq+7BxRHxry2Ozu" +
            "IYXqNi1XzBP9eKdGKVsQz6Ub89YRP2bn+3EN2zN+Oe/xZxlUYY04yv5f6nmdyL6BamNzG/ZtovtZjvKw" +
            "4MtYkDRB/Xgr4i5H2i95swYlZt00844WYx3a21lw0uK+vxVOTfleenFJfU9/zTO77QPNRovEhu7spG2M" +
            "lxZE7mny/YHNoZ9A2NBDE8GGlyGK0cn+NFGKe2Oktr1a9lgfGupcVkPo6H+X+/s6/gLwl3bi34GYcLyv" +
            "Gy+3iiVF8PONSba1cvD6ZZBFuVYc29dXTIM0p9wIKlsZb7C2wVCn4fKbIJX9FrRbwi/EmpS38p1JfAw3" +
            "mxHIfI9MSKzdqOrrJ7ysOZ732UPfYWGcj1llIfW1pEIFyL6Ct4o/VZHpiNQ8NeUz2aXAVe0juBVRYsjC" +
            "6hdNCP8xL/qveHmYO9Le4d7g34kl9LeT+6mggIGfpkTm8RanPf1oQfHa12PbenmLE/T3MtU59dTSoMZR" +
            "7ARWXLPS7Nw22zOWG5HeVdvGMF2J+Pu61rRiNlODLGWdT+T1ZSH0t5v7qaCCgIWtpTCTsrqmzTcF/Xik" +
            "SsaKUQTvm8Z0e1ir1KAGfXHE403T4eKZAfINckk5zotci9TX1Pc/kXkCDdnI7LrS69xh2pSE4MVtidVA" +
            "rWYq/Gveu63d8O2vzYzN5rr7k23x0qbhm4nuWnOhrSX1Nfc8zuRdQuuJ0NurOSOLFuuC3s8W25sgRcGT" +
            "MW3N+a1df1DaAOOVb/PaSS92/PhJlyYlezWyQCFaH1ba5F9BoKbnS055NnOH/bIbw1RWHj6ultmQwC8U" +
            "TY02GbzCHNVJcmjdb1aGtBJJ3L5f574rDFU8QrAoUbTnRHQSQWMF0K7lZUt/zTO5Hoh2ZpE9UAsnVltj" +
            "wXblWTvS1WCgeG7t5LhAk82a/vMPj40pxud5irATfLTh8t7BG2GIpJ3p6cznRkBTtDFTic95zgUCDCAR" +
            "wl5s8117oYpqnBfziDp/Jvo1d3LGS4m92NhkpbDwqpDnRp6oWG+1fpz6mPucdLQS0ZynN8/tGYcMX4mb" +
            "0WzFPTTTZWd5cE1F24MmdPgcHfG5FooUSiY+w4nPeyX0TBjBYVIw6EZXAYmZRbvrCL5/HitlbDvjJjrj" +
            "jQuCWVBwYidg32OB/ajY/eja1SK45RtRnxStN2AZ+bmZR0oySguU6rMgATQQEsK8c8Pm8xemaw87y+mu" +
            "mrs2J7jauDfeNhNxH0tRc2+fqJCf6dC3pT+0r61M0QosmDOCeIYVrJY/R1S6MtdwqOs2JrnqCKd/CtRJ" +
            "fdUEbAVlCsX8p8vz+aj5r6WTJiU592l/2tdpnQxsBAewbjilZiinf4mI9X1EoS070xXoSfUqWYl+PMgA" +
            "6RSsB2TLZewLg6/lCrmrpPDAWdhQ5wjipZg/ws0E/VzWPNoJWAgLYPRgzUQxZiCxOzq49iKcTJ2cdFiK" +
            "LiWKo5aYs2gkISDYusZLR3m80rrX8TdXmQtOmZCU+6YiWAioVko1LLKE4Vdez1vL5uuRUvYAlFI+Pedr" +
            "u5KPfP7/EaDHm8FKt5c/mXC1WcaZUfcFnSzWuD+/wtd7BR1sBQVJr+f7+FrESfHilqIWIqn5ia6wE9/f" +
            "rWeN6NVoLCODASMieYlKg8v3LxVw3Z+frkvcvJzP6e4oRBzSucZ2S3397gwgBD4/7y5Hok2oxlx3rb6r" +
            "JdlRp5NkOO/WARnNhN0MIuG80ZKgQc3LO5VS9wHwozYZzW8C2EFDK7oGYfsfno9kiF5o21SmRsy0v9e4" +
            "wr8W22vIyxWy6u3VsSwGlmG2/bz3bWkCQ9EHOXJWcbrjLC/bSetG7+iKGC6rj0nmxSnKYLyxafN9IdhC" +
            "CpDzL/rLPvuG4532wW822F1BKpAQ/zAvONBwqwUqijiOSJmbMiugvKIbsGNdKSqykVTIilSw39qNk6c5" +
            "CSzAbWUx7NsGqf2/UidhXDrhnSGmVkpGF20ZAq6l5gnOLFj/6NpVNlO1di1En5i43ZE+fPmmo3WRbPYV" +
            "tlMGi4r5iko4axEk11KovqIUW85HEi5PiTml9noJMCh0UZbLceNCOGHEVoyU9lt7cSm5LAa3GkXBnX8y" +
            "dfQB6rITIE7f5/WPIihGQIRNGQIZMGAEZMmEEZMiEEZAhE0ZAhkwYARkyYQRkyIQRkCETRkCGTBgBGTJ" +
            "hBGTIhBGQIRNGQIZMGAEZMmEEZMiEFELUe22EQU+EEHWpFNO9NsSgJ0oxLQVM9doQg54ImJIIIyBDhwi" +
            "mJHC213YYNEXxf9J2xHu9tsOgJ3ZB/EYopUT9ldIUqDt7bZBBJ8SlgZebk1IIoRDq3V6bY9AMod4VQig" +
            "JYFu83Wt7DHqRama5sMnCq+4nccwjvTPJoAtS8mn/Mf8vYdVUhmXLl3tnkkEnVmtlWUClF5tfIMU7vTH" +
            "JoA1SvFN6sfnF8svVn9lSHQPmttwogy7MLWlkmTYBlY/6Z22bZ6UwdU4M7UhBZNs8Wz7qtw08X5fOUT7" +
            "qn4glL26daQYdiCUvlo/6J659f818oMGX/Lek5M1bb5ZBB6TkzcGX/LfW/OxGB/Uf81/A4nnTnN2+SEG" +
            "ExfP9x/wXbvSddQvcNo67R8KQXwM7ummcIffMLfV5rmu2VrNuSmv5qH/CtjlkHvFvI6R4x7Y5tJ54YAM" +
            "RaDXN10sPRmH8ihmx3p5IyaeWLV9ePc6zHh3VaG8cd4+EEc+gxNNmFl93xCWEete2eHsjEee6o7P8tFJ" +
            "KeG+UHwgD9RSwF8WkgkkhmFBKDWQ5t6G7CCHqSjEtYGopC/Ws7Yj3ii80vhSi87L6/w9v/R8MOK1yZwA" +
            "AAABJRU5ErkJggg==")]
        public string ImgShuffleOff {
            get {
                return ((string)(this["ImgShuffleOff"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjMwLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0OToyNy0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0OTo" +
            "yNy0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpmMzA2MzZmNS1jNjQwLWJiNDgtOWU2NS1jZjMwYjIzZmYyNzYiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6ZjMwNjM2ZjUtYzY0MC1iYjQ4LTllNjUtY2YzMGIyM2ZmMjc2IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6ZjMwNjM2ZjUtYzY0MC1iYjQ4LTllNjUtY2YzMGIyM2ZmMjc2Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDpmMzA2MzZmNS1jNjQwLWJiNDgtOWU2NS1jZjMwYjIzZmYyNzYiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6MzAtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz6odgogAAAREUlEQVR4nO2de3AUVb7Hv6enJ/NgZvI0gZmExUgtbC6IRDbLXgxyNSVroaCiKZe" +
            "tW/gqagsQoXj94bVu3eLurQJJKSDUlgWu7NZalvKMsitWdAmRFRHCYhDBihEJE0jIax6ZR3qmz/2jmUk" +
            "m5NXdk0x3cj7/9Uw/fr+e75z+nXN+/TsEKqCUktCb1l9FBLoIQCEonBRwEoJJlFK7mnMzkgshxEcpbhC" +
            "gCQRNABp4IzlmXhv4ihBCFZ9XyUGBClNZJIpnQMligE5UenGGFiA3QWglb8CH1vXhKtlHy9k5+IZlbjQ" +
            "ibhNFlMq9EEP7cBxqDDy3ybIueHq4xwxLQIEKU2FEJK9DpE8pN4+hGzhyiOfoRuv6cMNQuw4poECFqSw" +
            "SwQcAMpNiHEMvdPA8yod6rHGDfendbnpZjOITMPGMRzLFKD7xbje9PNhOA7ZA/tdNb4oiXkm+XQy9wXH" +
            "YYdsYXtvfd/0KyLvd9DKi2DmiVjH0hQFrHBvCu/p+fIeAAhWmMjGKT0QKw+hYxtADHEGUM+A3fWOiBAE" +
            "FKkyFkQjOgsU8jP7p4HnM6d07SwiiIyJ5HUw8jIHJvK2ROPEWKPiGZa7QLX45+jYx9IYxjft1bLAx3gJ" +
            "FI+K21JnE0BO9tcIBtwNnNj3BGCaiiNJAhakMuC2gSBTPpNYkht6IaYajlBJpVp3BkAEliymlhLDgmaE" +
            "UYxr3a+52MhiDIZuIQBdxAApTbQhDtxRyoHCm2gqGTqFwchRMQAxlUMDJEYJJqTaEoU8IwSSOvT3BUAq" +
            "l1D5oRiKDMRRMQAxVMAExVMEExFAFExBDFUxADFUwATFUwQTEUAUTEEMVTEAMVTABMVTBBMRQBRMQQxV" +
            "MQAxVMAExVMEExFAFExBDFXyqDUg1rSEDPm2x44zPgkudPFpaogj7okAoAjEQAQBwVh4w8zDZDcjNNaA" +
            "oI4ISexCP5PqQY46m2IPUQrxbTYqLTOuVs61mvNWYjdp6EeGrflXnMk2xoXgqh9UFbZiTE0qShfph3Ag" +
            "oIBBs/eEuHLzAQbjWFf+cmA3Imm7HvXlRzLSHMNsWhMscgc0YhSNNujXebgK/YIA7xOO834I6nxnfNBv" +
            "QftkHGuppgYyTJ2DpLBGb77kFq3Fc3NaxLyBvmMNr9Xk4XhMG9QkAAJJpQsn9Zrzgase8nCCMnLJbIIg" +
            "Ep1oteMedhTPnQqAdYen8diMWlpqwZWozHCYxab5okTEtoF0NWdj9GQHt7AYAOGakY/NML550+WBQvjx" +
            "Ev0QpwWG3HVvrHPBe9AAASEYaVj1M8XJhe1KvpSXGpIAa/QY8cWIS/N9JP6RjRjq2F7fhwbzgqFy/utm" +
            "CDbXZcSHZfpGOIwtuoMA29gLuMSegk81WrPjICtoRBskxY8NDEbz0s46U2LL3p0xs/5wHbQ2BZJrw9uM" +
            "BzM8LpMSWkWJMCWhHQzb2VEYAQUR2cQaOz3fDbkxtDOITOCw86UJbbSdg5LByMY9XCttSalMyGRMDiSI" +
            "Flp93Yc/BbkAQMbfMgVNljSkXDwDYjSJOlTVibpkDEETsOdiN5eddEMfI31b3AhIp8OCJApyu8gJGDmu" +
            "eNmL/bDeSHCOrglBg/2w31jxtBIwcTld58eCJgjEhIt0L6Pl/udBythMkIw37lnVj1d3a7fGsursd+5Z" +
            "1g2SkoeVsJ57/lyvVJqlG1wLa0ZAdb3n2LgnggdzR6WWp4YHcIPYuCcRboh0N2ak2SRW6FdDJZqsUMAN" +
            "Ys8SgC/HEeCA3iDVLpKVI9lRGcLLZmmKLlKNLATX6DVjxkTUeMGv5sTUQq+5ujwfWKz6yotGvz7VtdCm" +
            "gJ05MAu0II7s4A+8Wu1NtjmLeLXYjuzgDtCOMJ07os86X7gS0qyEL/u88IDlmHJ+vrd6WXAiF5EOOGf7" +
            "vPNjVkJVqk2SjKwF5wxx2fyatD7PhoYgmxnnUYjeK2PCQFMvt/ozAG9bVT6IvAb1Wnwfa2Q3HjPSUTU+" +
            "MBC/9rAOOGemgnd14rT4v1ebIQjcZiQGB4HiNlC6xvVjdVIC7y4D9TVn4+JoZ3lsChLYwcDv7cNhYeRi" +
            "zTXDcZcRjk0NY7myHa4LyydLtxW1YcZHH8ZowAj8nuskn0s1c2H9fzsX7HwXhmJGOrx+9rugczUEDfl/" +
            "nxKUaD5I+DMwRFJWm448zm5BnUSakX/49H96LHjz7uAX/M70lufaNELp5hB28IJm6eaZX0fEHrtsxf58" +
            "dl6o7ky8eABApLlV3Yv4+Ow5cV1b4NuZbzFc9oAtLz7aaIVzrAsky4UmXT/bx//t9Ll59H0BwFPJxglG" +
            "8+r50Tbk86fKBZJogXOvC2VbzCBiXfHQRA73VmA3Ai5Jis+xMwgPX7fjL0TtHqR0z0vHctAAW5fjgskV" +
            "kp7UKIoHbz+NYqx3vXrHGk8cAABT4S2UQ05+14+n84QveQChK7jfjq6ow3mrMxrs52h/j0kULVFsvddd" +
            "fcMkbcW4OGvDqkT4jvDYjtiwj+PrR61hV2I4pDkFRTrSRo5jiELCqsB1fP3odW5YRwGbs2YECrx4xoDk" +
            "ob4Q55mPMZ62jeQG1hgwIX/WDmA2YlyNvvuv3dc7Ex5bNiMO/DaDcpSyOGoxylxeHfxtIFFEwKtkgg3k" +
            "5QRCz5HNrSPvTG5oX0KctUkCaNd0uq6Vwdxmk3lYvtiyOoChj5N7dKsoIYcvixOGASzUeuLuGLwQjR5E" +
            "5zQagx3cto3kBnfFZAAD35skLgPc3ZSX0thwz0kek5elLucsLx4z0ng9EKtkig1kTpcdXzHcto3kBXeq" +
            "U4vyZdnktx8fXEnsxz00bvWT2vtfqa8tQxHyN+a5lNC+glhap5Zltkxf/eG8JCduLcuR3/5XS91p9bRm" +
            "KmK8x37WM5gUU9kk30WWWN9UgtIUTtp0TZE5VqKDvtfraMhQxX2O+axnNCwgh6WbajPJuJukz2tw2ij0" +
            "an0BUHR/3NTR6oleK5gUUK7ESK3QwXDhHWsL2la60AfZMPld8poRtY7ZpgD37J+arKHeCNwVoXkBKySp" +
            "I/NHecSf2hJ46kw9BVNdSDMSfb2QmbDvuMg6wp/7RvIA4q9QT8XbL+7EXOLsTtr/6Zxd8Qo+731Z7MPe" +
            "YEze6ktvT8YY5nPhnYo/xscnyepAxX2O+axnNCwhm6Sb6BXkxzOrJrYChl+gCETx2Kj9hH/9lL/7jg0x" +
            "80ZK88ZZnzuXHy8gAADiC5U55UzBxX81MQKox2aWb6Q7Ju5kTrVFMmZuR8NnNrztQfjYfEdojLNoawov" +
            "vpaGiPkeVnSIFltXm4+qpxEzJotJ02YlmMV9jvmsZzQsoN1e6ief98luJP892A5bEH+HCPzz4ZWWf+Sl" +
            "BxNuHw4rjotOtFpT8LR/nPkucOoHFgD/ObJJ9vpivMd+1jObbyKKMCH4CUOeTnx+TZ4li21MiNn3AAUL" +
            "P7Hbg+/6nNL6t9mBusxMfP9SMSUOMG6256MT1AIfvGyIQGrsA9BEPAf7wRFRRdqLkq4CiDNYLU02JXRq" +
            "V/aZZ2b9xidOL/ysXAX54Lctw46Ljf/fh22rPbfH0gQD/udgiKxeoNxduSj9LzHcto3kBPZIr/Qjtl32" +
            "Ku91LnT5sKQcwzF6NqrjIYsAfngX+6+fKcpoFkaDjilQ5Nua7ltG8gHLMUZim2EBDUZxqVd5bKnd5Uf2" +
            "8F1PmZSb2zpIFR1D0YAZOvuhT3PIAwKlWC2hI8lkPNag1HwMBQPFUDl9elQYDF+Qqn1WfaI3i+L9fw/V" +
            "ZBjy8Z+CCBiTHjL2L/Hgg1zPgPv2/1qM+XUQa8PSgeKrm/9sAdCKg1QVt+BJGnDkXQvQ+orrCav4g3Wr" +
            "bdMewgugrq5L/YmOUEpw5Jw06ri7QRxk8Xch8Tk4IxskTQDvCOOweuSy9f3swHacXNQ0pnpHisNsO2hG" +
            "GcfIE3VS914WAAGDpLKkbvrXOkfyTGzmseNKEQyXXFRcdTwYx32K+6gHdCGjzPbdA7EZ4L3pQ3Zy8qQe" +
            "SY8a+Zd1YP7U1aedUQnWzBd6LHhC7EZvvuZVSW+SgGwFZjRQLS6UZ9g21ySkLZ5vuwD/KOzRR3Szm08J" +
            "Sk27eiwd0JCAA2DK1GSQjDd6LHuz9KXPoAwYh1fFOb/b+lCm1Phlp2DK1OdXmyEJXAnKYRKx6WPp3bv+" +
            "cT0jPkMtg8U5FfQ6KK52YtjsT03ZnorjSqXqydSB8Aoftn0ud4VUPU90tzqKb6hy9uf/jfPi/8yC7OAO" +
            "nyhqTVqXsRhePJTUT4anrf/wnfWY6jpbeTFqrRQkwr6oAbbWdsP0iHeceU1Z1JJXoqgWKcWTBDZBME9p" +
            "qO/FcbfJqLQ8mHgDw1HmwpGZi0q73XK20BALJNOHIghtJO+9ooksBFdiiePvxnlrLu39UX1uwoj5nUPH" +
            "E8NR5kvI42/1jVrzG9duPB3S7ko8uBQQA8/MCWLlYih12Ho2qzir866XhJ93L2bc/vmixYOdRSTArF/O" +
            "6XsFHtwICgFcK2+K1ll86alUloq7G4Xfl5ezbly9aLHjpaE+Na72v3KNrAQHAn+5zI3dOBmhnN158Ly0" +
            "pj7ORYvePWXjxvTTQzm7kzsnAn+7Tfv2fodC9gDgCVC/oWU5p5wEBy8+7QGVmbEwoGH7rJWdfQOptLT/" +
            "vws4DQrzlqV7QCG5k3ioaVXQvIEAS0f7ZbqxcmhYPrOdVFcgaJ/pdUffQOynY1ydwmFfVsxzVyqVp2D/" +
            "bPSbEA+h0HGgw1Cx5WfJJ/pA9sfSZ6Tjzm+GN17AlL3WK0kV3kzWQyBbdHSMoXfa7oj4Hf72UFu9tTSi" +
            "w4HdFg8/Ys2W/xyjeMIfX6vNwvCYcf2OUZJpQcr8ZL7jaMS8nqDgHSBAJTrVa8I47C2fOhUA7pDIuxG7" +
            "EwlITtkxt1t3cllzGvIBiBASCrT/chYMXOAjXel7FIWYDsqbbcW9eFDPtIcy2BeEyR2AzRuNVMrzdBH7" +
            "BAHeIx3m/BXU+M75pNqD9sg801PNYMk6egKWzRGy+55auUjLUMG4E1JuzrWa81ZiN2noR4at+VecyTbG" +
            "heCqH1QVtuklDTSbjUkC9aQ0Z8GmLHWd8Flzq5NHSEpUqg4Ui8fo8nJUHzDxMdgNycw0oyoigxB7EI7k" +
            "+Xbx6M5KMewEx1DEmBhIZqYMJiKEKJiCGKpiAGKpgAmKoggmIoQomIIYqmIAYqmACYqiCCYihCiYghiq" +
            "YgBiqYAJiqIIJiKEKJiCGKpiAGKpgAmKogiOEaL+ePkOTEEJ8HKXQZ2UjRsqhFDc4Ashf0IrBAECAJg6" +
            "ECYihEIImDkBDqu1g6BSKHzjeSI6l2g6GPuHTyN8IpZT4tlmaAJq88qOMcQC5ad8UdHKEEApCK1NtDkN" +
            "nEFpJCKEcAPAGfJhqexj6IqaZeKE1/+umk6KI0tSZxNALHIca28bwfKDXVIaB5zalziSGnuitlbiALOu" +
            "Cp8GRQ6kxiaEbOHLIsi54Or7Z+zueoxsBJH8xUMZYoeO2RuIkCMi6PtzA8yjnCMZ30RvGHXAEUZ5HuXV" +
            "9OGHg+Y50Duv6cJXIYd3omcbQAyKHddb14aq+n/ebD+TYEN7Fcdgx8mYx9ADHYYdjQ3hXv98NdJBtY3g" +
            "tDFjDHmfjF44gCgPW2DaG1w60z5AF9wMVprJIBB8AULdIKUNvdNyOee54bPVmyJRW6/pwFc9jDuvijyM" +
            "4cojnMWco8QDDaIF6E3zDMjcaEbexEeuxCcehxsBzm3qP8wyFojVjAhWmskgUz4CSxWwWX++QmyC0kjf" +
            "gw+G0OHccrebSlFISetP6q4hAFwEoBIWTAk5CMIlSaldzbkZyIYT4KMUNAjTdzkJt4I3kmHlt4CtClK9" +
            "7/f94CU+KhEcfHAAAAABJRU5ErkJggg==")]
        public string ImgRepeatOn {
            get {
                return ((string)(this["ImgRepeatOn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjMxLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0OToxOS0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0OTo" +
            "xOS0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDowM2FhNDUwMy1kNzdjLTYzNDUtOTU2YS0wOGI3NzU3YWUyYjMiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6MDNhYTQ1MDMtZDc3Yy02MzQ1LTk1NmEtMDhiNzc1N2FlMmIzIiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6MDNhYTQ1MDMtZDc3Yy02MzQ1LTk1NmEtMDhiNzc1N2FlMmIzIj4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDowM2FhNDUwMy1kNzdjLTYzNDUtOTU2YS0wOGI3NzU3YWUyYjMiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6MzEtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz7f7hwaAAARiElEQVR4nO2deXBUVb7HP+d2d3qhu7OSSBIYjMyICCrIMMxjWJ5So1Mo7pRD1Xu" +
            "uZVmiKMVi1Tj+hb4qFGpUdGqepTODVjlTiqKo88TCBRBFhCiD4lKIQEgwMWt30kt6Oe+Pm85Gtu7bne4" +
            "bzuevpO+95/7O7W+f+zvn/H7nCAwgpRShJ1y/ikbkEqAKSbmEciGYIKX0GClbkV6EEH4pOS2gDkEdcMx" +
            "qE287Hgh8KoSQKZebykWBTfbF0Rg3IcVSkOekenNFLiB+RMjtVguvuFaHdyZ9dTInB//knBuLxh+Lx5m" +
            "f7I0UuY+mscdi1dY5VwX3jfSaEQkosMleFY2Lx4nL61M3T2EaNPGaVZNrXavDx4Y7dVgBBTbZF0ejvAw" +
            "UpsU4hVlosVpZNtxrTRvqoG+j/b54jHdQ4jkbKYzHeMe30X7fUCcN2gK1P25/Ih7n/vTbpTAbmsaT7rX" +
            "hBwY6NqCAfBvt9xHjqYxapTAXFlZ614Q39//4DAEFNtkXx2O8E5dYRscyhRnQBDHNwpX9faI+Agpssld" +
            "FoxxA+TyKgWmxWpndu3fWx4mOxsXjKPEoBqewSyPddLdAwT8550Y645+Mvk0Ks2HL036dGGzsboFi0fh" +
            "j2TNJYSZ6a0WDLsdZTU8oRkg8zvzAJvti6BJQNMZN2TVJYTYSmtGklEKfVVcokkCKpVJKIZTzrEgVW57" +
            "2a60rGEyhSJpoRC7RgKpsG6IwLVUakvJsW6EwKZJyTaIEpEgNCeWaEEzItiEKcyIEEzSVPaFIFSmlZ8i" +
            "IRIViOJSAFIZQAlIYQglIYQglIIUhlIAUhlACUhhCCUhhCCUghSGUgBSGUAJSGMKabQPGMrUdFrbUFfH" +
            "WSQe+nyJEmsIA2IrteMfbuGpSiFvKm6kYF8uypakjfBvsKS9vphiY+qCFuw+Xc2RPG8SHebyaYNr8fP4" +
            "yo44yp/mEpASUZrae8vDQ6xYIJikGp4VHr41xY6U/M4ZlCOUDpZFHvivloX+SvHjQr3non3oZZkIJKE1" +
            "sPeXhxTeCMER7rpW5cE7xYJ/sHvgECS9uD7L1lHlCtJSA0kB90KK/tobhH1e18sV1dbx5ZePgJ0l46HU" +
            "L9UFzrK5z1vfCGkMW3m3wsN/v5EirlYaGGGF/DEJR4oEoAGKcFYvLhs2lUVpq4aKCCHPzO7r9lbsPl0O" +
            "wdfCbaIKFiz1cUlQ7MqOCMe4+XM62OTUGa5d5zkoBHWh08HRNMdVH44SPtwMxoH3Q82VrJ9HWTqLAiaN" +
            "wAvhgqpcbK/3Udlj03tYAzLwsn1/mh7iqpI3zC3xJ2XhkTxu1F1pyvot/1ggoEBFs+H48rx7SiJzsAPQ" +
            "vVDgsFE31cFFZjBmeEDPdQSocUdy2GN483aHxdQp8ESv1YQsHfU4+9ztYUNgBwJa6IoiHBrznmp81Mrt" +
            "k4GPDEpdsqSviDz//KbXrR4kxLyBfWOPho2Xs2BNG+oMAiEI7cy51cHtFM/NK2rFprUOWUeyQFDs6Odc" +
            "Dc0uCfY69ddIBDCySJ06WUNUYAaDSHuGuc5uTsv2tkw7+8POkLhl1xrSANh8r4pn3BLJVfz15p+fz4Aw" +
            "f11U0YUl9e4g++H6KDHrss/fa+Kzrb+cUD3edm76yc4UxKaCadgvXfjiB9q9138Q7PZ+Ns5pYWHYq7fd" +
            "KTE9kgkyWnS7GnIB217u4600XsqUNUeJgzWVR7vxZ+oWj0BlTAnryWDF/3h6FSJjiWQXsWFCLxxbP6D1" +
            "txXYiXd39TJSd64wJAcUl3PZFBft26j2ruYu9/H1WDWlyc4bEO95GU4aGa7zjbZkpOI2YfiQ6LmHhhxN" +
            "18dg0Vt5oY8vM2lERD8BVk1Lspme57HRhegHd9kUFDQdaEQV5PL+8kxVJdpWNckt5M2gp7ds3NJrQy85" +
            "xTC2gJ48Vd7c8z10T4DelweEvSjMV42JMm5+f9nKnzc/P+VFoMLGAdte7dIcZWHmNJSviSfCXGXXgTOP" +
            "kp9Oil2kCTCmgmnYLd73pgkicuYu9o/7a6k+ZM8aj18ZS3IG2HwIevTZmmuhEU0YkXvpWJe1ft1E8q4C" +
            "9i0entzUSHvmulBe3DxITZBGI/DwAREwSb+s88xwB/7XUyR9/0ZBZQ9OI6VqgzceKaP9aHyTcsWD0els" +
            "j4Y+/aODRmxn4dRaTyOYwsjk8sHicFh69GVOJB0wmIF9Y45n39PfEmsuiGR8kTIUbK/3svsPPtIUFI+u" +
            "daYJpCwvYfYffdPHQYLKBxIePliFb2/FOz8/p6YkyZ4xtc2qovXCkaT36AOhHDU4+9Y1j9ZQhIhZzDNP" +
            "4QIGIYNbzhUh/hGf/O8rCstR7XQPmayU7HeGypjW/6wd/Hlf+rx3Nm0f17U04TfLTNomZsOH78Uh/EO/" +
            "0/JRn1fvma4UYLI5nRASiRAJRmmpgSzVs0cYZyu8619OJ+/zxtH/jY/PxEtaZpBUyjQ/06iHd1AdnJBc" +
            "ammDrKQ8LnvdwZFfr8Ml+qRCXHNnVyoLnPSlnVay6WI9yfOGAaX7X5hDQgUYHkZMdiCI711Uk72g+8l0" +
            "pD/2D1PK1ksVAftfyia1oJQ4iNR0cbHRkwLj0YwqpP11TDPiYM8uRdCRhd75WP7zT87n1/ABLSvxUuKP" +
            "YtOTKjcQFte1W3m708PdvXfi+7BVY35XfNfVmT1I9K03AjBl2Dn0QYkt9IZeWnE7Kpmxgihao+qjeXb+" +
            "9IrkR5wHztdw21i8XfPa7U6yoamayN5K0eABsmmSyN8KKqmY++90p1i8X4O4VfpFiftctFa0AfPh1BiZ" +
            "oM0DOC6gxZCF8vB3hsDCvJLmel56v1eu15bax7fcBllWk5kcNxbIKH9t+H+groq78rmS44pwOcFkJ/+D" +
            "ndEfuvyByXkDvNugOadFUT1ItxUD5WuuXRplWkLkYm2kFIdYv7TsccGRPG7UdI2+FrEKSf944APa3udJ" +
            "qXybIeQHt9zsBuKgsOQdYz9fqEZx3en5GWp7+LKvw4Z3eK7yjK78rGS4o0+3+uM2ZTtMyQs4L6Eir3oz" +
            "P8CTXcuj5Wj3cen4gbTYNR/979bdlOObk66/q6qbcj4nOeQE1NOgtz0x3cv5P/5yqJSWjN8/U/17J5nd" +
            "d6tXr2tiU+yEdOS+gsF9/iBWO5KYa+udUlY/LTObEQPS/V7L5XYVW/frIaIxbGSTnBURIf5huW3IPU/Q" +
            "bbW4Kjd5yKf6IsS54Ydf0ZLRj9ESfKjkvoMQSK4mFDkaK5s3r8/+3HXmDnJl+vvX39V2Sze8qtOs/Fun" +
            "P/dTmnBdQqhRN7Pul/bW2b0/o+v2VROKZGax74XRhn//NkN+VKjkvIM2l98J8ncl92YvK+0b9ffpxB/5" +
            "IT3W/2tXG3LfL0z5Y5wtrfPhx3x5jsvldibom6p7L5LyAcOgPsT2SnA9z76RGsPQSXSDKVXsr+5zT/o2" +
            "P/3y5kI8a0jfectPByr6vnhTyu7rr6lACMozdoz/M2lByD/McV4zJcwv6fPbjZy0sO1BJVPYISzaGuOO" +
            "lPDYdLTFkZ1zC8upKju9t6fN5Kvldibom6p7L5LyASkv1h/h5e/KtxAsza88IcD/0QRu/3N5vfioS59l" +
            "t4ZT9on2NTub8q5KD7/Vb6i7F/K5EXRN1z2Vyvo2cVhDlBHDYn3x8TJkzxmPXx1n3sgaRngD8wHcDT2l" +
            "8tauNufXlvHVZPROGGTda+WU5pwIa3x2LEqnpAPqJx0B+l17XCNMKVDfeMHM8+qjsv+tT+zVeU+7jf5b" +
            "FwTqylmWkftGO//Pz1a62LvH0oyu/K9Usi0M/6l9Lou65TM4L6Lel+pfQ/I0/5W73DeV+1i8DRtirMeQ" +
            "XGczvisQFLd/qS/Il6p7L5LyAShwx7JPdyFCMvY2p95aWVfjYdZuPyfMK+/bO0kWa8rv2NjqRIb3OJY7" +
            "cn8rIeR8IYNYUjU+O64OBi0pTn1U/xxVjx3+c5NTFFi7/8+CxNqLEwXNL2vlN6cDrPwODpPUYDxfRBzz" +
            "bmDUl53/bgEkEdO/EJj7Bxv6DIWKXCMMrrFYO0a12T/WOyIn+dkXLkMdTISYF+w/qg473TmxKe/mZwBQ" +
            "yn10SwjZpHLIlzLbazG1EcuHCfPYtqRtWPJliW60H2RLGNmlc6guUjzKmEBDADRfr3fANh73pL9ymcdd" +
            "1dl6bcyqlAPt0kahboq5mwDQCevC8nxAeG74v29hVn76pB1Hi4PnlnVnPR99V78T3ZRvCY+PB83J7e4P" +
            "emEZALpvkivn6DPua6uK0lOme6uWDZS1ZXd0sQaJOV8y347KZYrkCwEQCAlg/pR5RkIfvyzaeO1E4/AV" +
            "DkG1/pzfPnSjUW5+CPNZPqc+2OUlhKgF57XFWXK7/Oje+b+0TnpEs2fZ3EvgjGhvf1zvDKy6XeO3m8X/" +
            "AZAICuK+qGfcF+cjGEFfsrkCaI4FzQKRAr0NjCPcF+dxXlfvL+vbHdAICeH3RaUShnabqVm6trsi2OSl" +
            "za3UFTdWtiEI7ry/K/Tz4gTClgCa6Yzx7dQBsGvt2+njmh+QS93KBZ34o6l7j+tmrA0x05/60xUCYUkA" +
            "AC8oC3LNU9x2eeiOW1qjCTPNRg5On3tAFc89SKwvKRi/pMd2YVkAA91c1MXexFyJx7nzDZQoRfdTg5M4" +
            "3eta4vr/KHFMWg2FqAQH87ZJaSmcXIFs7ueOlvJx+nT3zQxF3vJSHbO2kdHYBf7tkhLs45zCmF5AmYNe" +
            "imu6W6KmtEW75PLd6Z1LALZ9X8NTWSHfLs2tRTUb2aBltTC8g0EW0ZWYt99yQ1+1Yz9s50dA4UbrwRzT" +
            "m7ezZjuqeG/LYMrN2TIgHTLTM70jp2fIy3GvLy/SHXoyE504UsvF9K7IxhCi08+zVAVM7zAMx5gQEQ22" +
            "6OzpzXrvqnaypLu5eN9F9QT6vLzpt2q76UIxJASXo2fZbz1Lt2fbbn7ZtvxPEpGBbrYcNh73dwhEFeay" +
            "4XJpyhHmkjGkBgZ5q/PDRMnbsCXdnjIpCO3MudXB7RTPzSoIpz4lF4oK9jU7+WlvE/oMhZIu+jIvw2Lh" +
            "ivp31U+pNN7eVLGNeQAkCEcGG78fz6iGNyMmeVBzhsFA01cNFZTFmeELMdAepcERx22LdK4L4OgXtEQu" +
            "1ISuftzs57Hfw73oLzd/4kaGe15Jt0jhuuDjOg+f9ZKqQDCOcNQLqzYFGB0/XFFN9NE74eLuhsuyT3cy" +
            "aonHvxCbThKGmk7NSQL1pDFl4t8HDfr+TI61WGhpi+qpooWj32kSaywoOK3aPhdJSC9MKoszxBPltqd8" +
            "UqTeZ5KwXkMIY2R9pU5gaJSCFIZSAFIZQAlIYQglIYQglIIUhlIAUhlACUhhCCUhhCCUghSGUgBSGUAJ" +
            "SGEIJSGEIJSCFIZSAFIZQAlIYQglIYQhNCJH76+krchIhhF+TEnOubKTIOlJyWhOQ/IZWCgUgoE5DKAE" +
            "pUkRQpwHHsm2HwqRIvtesNvF2tu1QmBNrnviXkFIK/2POOpDnZNsghZkQP3rWBcs1IYREyO3ZNkdhMoT" +
            "cLoSQGoDVwivZtkdhLhKa6V5orf1x++54nPnZM0lhFjSNPe614QXQayrDYtXWZc8khZnorZVuATlXBfe" +
            "hideyY5LCNGjiNeeq4L7uf3sfs2pyLZCdFSkVZqClSyPd9BGQa3X4mNXKMk1wdi96ozgDTRCzWlnmWh3" +
            "uM/B8RjiHa3V4Z1xj1eiZpjADcY1VrtXhnf0/HzAeyLsmvFnTeDLzZinMgKbxpHdNePOAxwa7yL02/AA" +
            "WVqrX2dmLJohhYaV7bfiBwc4ZdsH9wCb74miUlwFjm5QqzEZLl89zxmurN8OGtLpWh3darcxWXfyzCE2" +
            "8ZrUyezjxwAhaoN4E/+ScG4vGH1Mj1mMTTWOPxaqt6z3OMxwp7RkT2GRfHI1xE1IsVbP4Zkf8iJDbrRZ" +
            "eGUmLc8bVRm4tpRShJ1y/ikbkEqAKSbmEciGYIKX0GClbkV6EEH4pOS2grisK9ZjVJt52PBD4VIjUNw7" +
            "5f5i8X3eQ03pZAAAAAElFTkSuQmCC")]
        public string ImgRepeatTrack {
            get {
                return ((string)(this["ImgRepeatTrack"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjMwLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0OToyMy0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0OTo" +
            "yMy0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo1ODBkNDA5OC1hMmM5LTA3NGItYTA1ZS0yMDE3NTZmYmVmNTgiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6NTgwZDQwOTgtYTJjOS0wNzRiLWEwNWUtMjAxNzU2ZmJlZjU4IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6NTgwZDQwOTgtYTJjOS0wNzRiLWEwNWUtMjAxNzU2ZmJlZjU4Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDo1ODBkNDA5OC1hMmM5LTA3NGItYTA1ZS0yMDE3NTZmYmVmNTgiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6MzAtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz4KNte+AAAPBklEQVR4nO2de28cVZqHn3NOdVV3+34Zx/ZAEiIUtNoQYJURjMJlgcxqEBLaHQn" +
            "mU8CCQvgOC0TA8i1AYiQkFjRihhEQLQhmJyFhR0RsyIXYCdjt+NbV1XU5+0d1GbdJYneX7e7jnOe/vlT" +
            "V+1b96pz33N4jyIHWWtReL98fhfpJYB+aSQ2TQjChte7Lc27L5iKEWNSaaQFTCKaAc05BvFd8vvq5EEK" +
            "3fd52Dqoe945EMU+jxVOgx9u9uKUbEFcQ+l1H8Xb5aPBhy0e38mf/tdIDcZS8nCQ81OqFLN2PlHyiHPl" +
            "S6QX/s40esyEBVY97+6JEvEKif9e+eRZjkOIdR+pj5aPBufX+uq6Aqse9I1HEW8DQphhnMYU5x+GZ9ao" +
            "1ebMfF171nk1iPsCK51ZkKIn5YOFV79mb/emGJdDSK97rScK/b75dFtOQkjd6jwXPX++36wpo4VXvWWL" +
            "+c0utspiF4rn+F4M31379MwFVj3tHkpgPEo3aHsssJiAFsVT8dm1M1CSg6nFvXxTxJTbmsVyfOcfh0Or" +
            "WWVMQHSXiFax4LDdmqKGRFVZKIP+10gNhPfnv7bfJYhoFV/4662xcKYHiKHm5cyZZTGK1ViQ0Amc7PGH" +
            "ZIEnCQ9Xj3hFoCCiKebqzJllMI9OM1FqLdFTdYmkBLZ7SWgthg2dLuxRc+WvZmAxmsbRMFOonJbCv04Z" +
            "YjGWfRDPZaSsshqKZlBorIEt7aJiUQjDRaUMsZiIEE9KunrC0i9a676YzEi2W9bACsuTCCsiSCysgSy6" +
            "sgCy5sAKy5MIKyJILKyBLLqyALLmwArLkwgrIkgsrIEsurIAsubACsuTCCsiSCysgSy6sgCy5cDptQKc" +
            "JE5j1JZVAsBAp5mNJLYFQC+pJ+h9XQkFoihIGVEK/EzPsaUZKCYVb/BW8JQW0UBOcX1Z8HzjMhusrwI/" +
            "BR7AA/IAEHFhMfxspJNzmReztiekvtp2v21huGQHFWvDdvOBstcBs+FPytYKAiWLEqIrpdTUDToKnwHF" +
            "AiexYiCIIYpiPJEt1wUysmK6lApwNXU4twUghZn855I4BjWo/+btRiIX/8Ha0p1EiOHtNcqbqEcTpdyU" +
            "Fd5br7O6JGXQ1sq18/ZBouFYXXFxWfFt18Rvn9xQcKAfsH0xw5I6+vTtbQBcWJF8sePhxqpBJL+ZAf8h" +
            "YT8JmFxBawA/LkjMLBaaCtIQrKc2v+gP29Cebe7EuYkcKyK/DiTmX6VpaQ096MfcN1hnephilUhP87Zq" +
            "7IqSJYsThoTold1suv63sOAHN1iQfzRTxY+hVMYcG6tze1xkXLy0Kvpx3WYoVJQWPjtYYKe6s0mhHCej" +
            "CouTEnEesBbtLEYdHw47HIFEiODFT4KLvoITm8FDAnr6dI6Id0YuhNXw16/BxpUisBXf31XlkrN5x8QA" +
            "4UvPIWJ27++rEWvBxpchXsw6686ZtCsY347WGT3/wOF9TSKF5sEvf8HuHI4YKCZ/OeZxacpmPFA+OBYg" +
            "2W4DdgvEl0OmKw/maoqQ0T+yqdaV4Mvb0JTyxq0ZJac7XFKcrxr+/ZgvowqLk1JKLFJrHflFj2IBwbth" +
            "LbZVCc2rJ5cKi0Y/AXAHN1tKAGeDBocAI8WQMe2lVC3BizmO2ZuxjMFNAfh0+mvkpYO7mautG7OlLVgL" +
            "rj2aK+PVOW9QeRgroxFw6bLC7FHHvcNRpc9rm3uGI3aUIP059MhHjBHRhQTJdc+hVMYdHw06bk5vDoyG" +
            "9Kma65nBhwbjHYZaAokTwxUIa9xwa6I5+nrw4UnNoIK2/vljwiBKz2vVGCejsNYkfCya9uGPDE1vB7X2" +
            "aSS/Gj9OZAyZhTEdErAVnqmnpc99gvogziODysuJSoFiKJEuxoN7im+9KTa/S9DoJt3sxv+yJ8XLczfs" +
            "G60xdLXGm6nHXkG/MfCJjBPTdvCCI05H1dkfV6zF8VSnwje+Q6HxVRT0RVBJBJZRc9B3kvOauUsTB4RC" +
            "3jc1Ch4tpKTQVKL6bF9w5aIaAjCkvz1YLABzoby9wvroMf5gq8fdqIbd4rkeiBX+vFvjDVImry+2dI/M" +
            "t89UEjBDQQk0wGyp6pGasp/U+n3Pzij/OlFuuptqhngj+OFPm3HzrxdBYT0JJwWyoWKiZEUwbUYWdX04" +
            "fxr6esOWZhFeX4cQ172ffT3oxd5ZDxooJxQItD2pqDbUQfqhJvq3+NAsx48Q1jx6nyq6ejZ9T6HSq7el" +
            "Fl/PLioPF7u/jMqIE+j5Idb67J27puHoMf6mUmr7zlOY3Yz6Pj6dTTUtu6+KB9JiSC3v6Ex4fD/jNmI+" +
            "nmtX9l0qJemsmr/iY+dztdL2AwgRmQ0lBwKDbWvHzVaXQVG15jRH78dLmB6jjpfTcq0VUTwRfVVqLZwZ" +
            "dTUGkPocGjNB0vYBm/dTEiWLU0uqJIIJv/Oa3+OGRGn2FrWvd9BU0D4/Umr77xncIWqiJpIAJNy2FMt+" +
            "7ma63sBKkqhlVrdUFl5dVU2tr0ou3pORZy3gpbY5nJFpwebm1gHq0kCou872b6XoBLUTpze9tsfq6tCa" +
            "ovbO8feNma6+11pb1yHzNfO9mul5A83Fq4oDTWkCwFDW7NraNqyHWXmutLeuR+Zr53s10vYW1xrPwWnw" +
            "Zl+Lm4t/bxr65tddaa8u6xzd8rdkgOj9hI45xWmzV6jW9zfVo++KJOGeolfkabkGP+WbT9QLKUqyoFu9" +
            "lSTa/vtVtfJuXg+bPvao1RWW+1m0J1DmG3ea7f3FNS+h/ZgokW9Qou1xtvlZvi/GbSXS9gNyGha1WC+N" +
            "uc7P/m2qhabLW18sF/nzFpRZubjURJYKv/eahk9u91rogMl/drn86Bgio0Bj8ilocFtrdGyNXLf+sx4L" +
            "Pf2yedzxdd3j/qrup/S1/nXFW0sgASKH5ZYtDMJmvBQPmBHW9gIoNC4MWx5Q8B+4sN6vuXE1x8keH1RX" +
            "KUqz44GqR8znnI2sNJ2cdzvrNTbC7SlHLE80yX4td/3QMENCAavSJtNiXAnDfSIi7Zt706arLn64Um76" +
            "LteCTuWLbcdG1AP50xeX0UnMJ50rNweHWOzAzXzPfu5muH/Ltd2LAYaneejXjKnh0pMaHjTVkGVeC64v" +
            "x6+UClVDw4GhIcZ0xs/+tKGqJZDpUVOrXP98/D/ttzU7MfE197266vgTKVpzOxO1164+VNY+P+ig2VrR" +
            "sNC7666KXCu4G4jk8GLQ0F2g1M2H6Xpuw2rbrBTRSSovx6ZrTdrN7VxkeG6vhbrA/Jk9c5ErNv4xW2Tf" +
            "QXumRaJiupy9L5ns30/UCKsg0lW7YSGjZLuMlzb+O++wvhU2ts81CCs0/lEP+bdJvu+SB1MdQpz6bkIO" +
            "662MggNu8iNnQ5eKyYthrf5qn58D9YyH3RiFvXS7f8H+9KuaRX9RvWoVs9rKejKzD87Ycfm4nRghob0/" +
            "MqSX4tupyz0iUO8PqzR70hBttKIj+/e1+PiOugxapj5D6bAIGFJLQX9SMFGL8OE2lu1X8Y0/IY+P1dcW" +
            "zVfywLPHjNGG5KVnvjRAQwP7GJK0zC5s/L0MJzUNDNf5pNGw76fhmkPm2fxsnv+XFGAHdMaDxFEwFiso" +
            "mrpnqVTG/3VVjb4eTgVdqgqlA4anUV1MwRkBKaA6U03kSf7u2Obl0JtyIJ3bdPFjeLjKfDpQDY9bFg0E" +
            "CAtg/mFBSmqlAcWkxXynU6XhnNZcW09KnpDT7B7u/72c1RgnIkeneEwBfzru5cul0Ot7JiJI0mz3Ar/o" +
            "D43IeGSUgSFeCThQjlmLFiRlzkhDciBMzBZZixUQxMnJTFuMEBKQblyi46DucNDjX8smKw0XfoaRSn0z" +
            "ESAGV3HTjEiU0pxfNzLV8YVFyetFFCc2jozVjd/Ix7843GCkmHG7kWv50zjNiFWdGJRB82shxfXgoMHo" +
            "HH2MFBGmu5Xt66yRa8Ocfi0aIqBKktiZacE+vmTmuV2O0gADuHo7YW0wTVL5/tdjV1dmFRcn7V4v4sWB" +
            "vMeZug3NcZ3Tv3d4gQsCDY8FKSfRxpdiVgfXJSrodVVby7ISdesCQ0fj1EAIOjkQMuAkn5jxOL7rMR9J" +
            "uOLcN7AgBZezpS+gtBHw0U+Si71CZEl225aXZAfP12FFbXmbYTXe3jx0poAy77ffWs6MFBGkMcvaa5Ez" +
            "VW1mwV1JpNtTdPTGDrm57TCxpzNO+uKz4tpruIARpepYD5YD9g0nHY7CtZscLKCPWgu/mBWerBWbDn5Y" +
            "IFURaxYyqmF5XM+AkeCpNsZJlyYh1utw4iNNFf0t1wUysmK45hKvu3kghZn855I4BbdSUjDzcMgJazUJ" +
            "NcH5Z8X3gMBvm68kYKSTc5kXs7TFnGupmsqNaYRulv6g5WIw4SJSmEfYllUCwECnmY0ktSZM7Zfl5XJk" +
            "mOijKdLlxvxMz7GlGSmYsvdlKbkkBraYgYbwnYbwHwIyVEN3ELf7+WPJiBWTJhRWQJRdWQJZcWAFZcmE" +
            "FZMmFFZAlF1ZAllxYAVlyYQVkyYUVkCUXVkCWXFgBWXJhBWTJhRWQJRdWQJZcWAFZciGFEIudNsJiJkK" +
            "IRak10502xGImWjMtBUx12hCLmQiYkggrIEubCKYkcK7TdlgMRfN/0imI9zpth8VMHFf8l9Bai8WXS1O" +
            "gxzttkMUkxJW+l/xJKYTQCP1up82xGIbQ7wohtARwFG932h6LWWSaWUlssvSK93GS8FDnTLKYgpR80ns" +
            "seBhWDWUoR77UOZMsJrFaKysCKr3gf4YU73TGJIsxSPFO6QX/s5WPq39zpD4GzG27URZTmGtoZIUmAZW" +
            "PBucch2eksHlOLM1IQew4PFM+GjR1PP9sOkf5aPBhInlh+0yzmEAieaF8NPhw7ffXnQ/U/2LwppS8sfV" +
            "mWUxASt7ofzF487q/3eig3mPB8yies9XZrYsUxCie6z0WPH+j/6yb4LZ63DsSRbwFDG2mcZauZ64R8/y" +
            "s2lrNulNay0eDDx2HQ7aJfwshxTuOw6H1xAMbKIFW479WeiCOkpdtj/XOREo+UY58aXU/z3q0laO9etw" +
            "7EsU8jRZP2VF80xFXEPpdR/H2Rkqcnx2d59Jaa1F7vXx/FOongX1oJjVMCsGE1rovz7ktm4sQYlFrpgV" +
            "MNWahnnMK4r3i89XPhWg/rf7/Awfj1flZg1gWAAAAAElFTkSuQmCC")]
        public string ImgRepeatOff {
            get {
                return ((string)(this["ImgRepeatOff"]));
            }
        }
    }
}
