//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarRaider.GPMDP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgNoToken {
            get {
                return ((string)(this["ImgNoToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgNoConnection {
            get {
                return ((string)(this["ImgNoConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAAAXNSR0IArs4" +
            "c6QAAEOVJREFUeAHtXWmQHVUVPrd7QkCIIQRZoozJVBISIGwGSUpZigpVKssPraBluZAUaLkFKAQVqhS" +
            "1lBIKNSBuUIlS5UaUHylZSlMWEiQgm4CQDZIwQBKWECI7me7r+U6/7umZvHlL95s39753TtXM69d97+1" +
            "zzv3eXc8511AJstaaaU+ef6KNojO4mD4iO4UsTSFjDuVnE0oUrVlbrAFjzKtk7TYytJXI8B9tMmF46+b" +
            "pN9zHz2zR15kiGXs3LF5AkV1oyJ7Nbz6kSBmaxw0NMAC2WzIrKTQr+mcuW9UsV00BaOrG8+bFUXQVI/m" +
            "kZl+k6T3QgDGrgzC8dMuMG+9tlNuGAMQtTp+J7NWW7McbLVjT+asBQ+YWG5pLuEXaVE+KugBKuqv4Zi5" +
            "oUr3C9HlHaWAnhcE59bq1oJbIvWsXf43i+A5Oo+CppajOfDYJdS8YqCHfiC1Q77pFP+WxzgU18uqjbtG" +
            "AMUv7Zy2/sJq4VQGUoC6+tloGvdetGgiW9M9edt1w6fcAkIx50G1ZCocn1u9drAFDEQXBR4aPiYYACLM" +
            "tiuIHWE065ulirNQQHQPrufnZ2ZBBNKbqCp4a6tNHkyoYyTSRtUCySDgwsCZ7oheqgRE0EPT0zE8XG7M" +
            "WSFaYR8igt1UDeQ3ksSIAkoGzbk/kdaTXtTTAWBHMcJqkBeKN0Vrp9ZlqYA8NVDATwCQDu+p7JNAbqoE" +
            "aGhBLDGBHB881tKSPamoAg+mgYgxWM6E+VA1U0wCwgzFQX7WHek810IAG+hhAbIaqpBoopAE7JRAb5kK" +
            "ZNVPXa4Dt3wMYwHe9IlQBxTTA2ME0Xr0niqmv63MBO8lCYterQhVQVAMKoKKa03yiAQWQAqGUBhRApdS" +
            "nmRVAioFSGlAAlVKfZlYAKQZKaUABVEp9mlkBpBgopQEFUCn1aWYFkGKglAYUQKXUp5kVQIqBUhpQAJV" +
            "Sn2ZWACkGSmlAAVRKfZpZAaQYKKWBnlK5OyHzK++QfWQH2U0cRrn/NbLPvE52124ybw6QfWNAJDTv6iG" +
            "7Tw+ZiePIHLYvmd79yPRNIHPMZKL99+oELRSWoSsBZNe/QvGqrWT//aIAp5r28pG37a53iPjPbmcflvW" +
            "7hiQXIH3wPRQs4Pjqh+8/5Fk3fDG9a8/N66pzZX4zonjl0xT9tZ9oy2uZnGbvkMzRB3DlTyQ6jFuWXm5" +
            "hJo9PWhxueUBoiaRF2vE2t1KvEz3DLRUDyT76Mtm3oqwsmrofhWf2UnD2+4n26Y4Ab50PoNd2U7RiM1n" +
            "8vbo7qexJ4yk8/b1EJx9CwRHcaowrOBTcHVP8xCtEd22n6O/PEe18W8o3E7irWziNQv6j/cYNAqwDrzo" +
            "aQPFtz1D0i7VEPM4BmWMnU/ipPjLzDiIO7d/a6ow4DPu9L1D0x01k/7MjKZvHR+GXZlPwscNa+y6HSut" +
            "IANnn36Touw+TfexlUTWAE5x/OAXcVbWDYu7a4hvWZ0Aycw6g8DvHkTl4n3a8vq3v6DgAATQDlz+YdCc" +
            "H7k3hl7kFQHc1BhRztxb9nFvAl97isKXjqecHHyCAqZOoowAU38pd1jWPEfHYBN1UzxXHE+07xhPN1wd" +
            "o4IqHpHvDWCu8eA4FZ3ROlxZO/OqxV3j/i4gtRdevpfhX64j4OvhkH/VcfizRXgUHx61UCPMgLSDP5GT" +
            "WdvfzRHwdzD2QB2UtHoe1ku8Gy/K/BQJ4LnuA4n9xxeAXfsnRFHz0fQ2K395k8e3PUnT1o9JCBh86mMI" +
            "fzuUgg36DyIGfaLlKxBhDwMMznp5r5zsLHkgJYINHrF6DZxkflRN/zHN7DSCMeeI/8ZFW3PL0XHkCmaP" +
            "cD7APHsEreAbvkMFn8hZAmG3JgJm1j27LB/CkQAGv4BkEGdLlhvS5T59eAgjrPDJV59kWBsyujnlqAQE" +
            "8g3fMGCELZPKRvAQQFgmxbYCpeviVI3zUu/AM3mVVnGURmTyUxDsAYXtCmnxeJJR1Hp8nMcy7yMCyQCb" +
            "I5hv5BSBsjGJviwkrzGO+SNiK2uaFTpGFyxLZWEafyCsAYVcdG6OytzXa2xO8/RAtfZwGFq8e9ZYBC42" +
            "QCbKJjB4hyB8AsT0PTDJA2BgdNWJLxHjZBtr96Tsp/jObgGzcRdGv14/a69KCU5lERpbVF/IGQDAGgz2" +
            "POY531kdjV53N6mI2NgNwouUbiBhIGe3gzdBRJsiEVggyQlZfyBsAiSUhazXE1LfFFLNp68C5/6ToR7z" +
            "NgJ3zJij69kO0+6y/UfzbjWy62ETGKklhqwRKZa2SxLlbY7xV3Zg+YMMsZqgHjE+mvY1lq5sKhvTx9U8" +
            "QAFSU4s3/S8YuN7L9z3NvUHjZMUWLSmRjsw/ICpmNBzbWXrRAMIAHhQvYrqcVloQYIHNrg1anWfBEbJo" +
            "xcCa3OLcnU+58i4h7pboflk1MbVnWVGYR3OF/XgAI3hNCbMNcivIDZBjXF+hy4jUvsNsPz5aufITswzs" +
            "ogBH9hw/O2Ip+tpbss2x4X5QqMmYyFy2nTfncBxD8trirgfeEGMAXVMyIA+Qmy8u2TRh8Az9m4zW2hQ6" +
            "+eQwZXgwUAkhxvyBBRsgKmVNb7oJFtSWb8wCC0x8IrjfYwS5KRQbI1d4VLD6cHQwrzoQ8VgEw8T34+pw" +
            "seXz/S2TX8ritCLGMZk5iVZDKXqSYduUpXiNt4lB+ifwu8dtq9J1wt2F75IEv3N1ojobTmXePo2DxzCx" +
            "9fMsWuYaBWJ7H+CaelRUkM2t/yZnKXrCYtmRzH0DsbizETn91iddrsIaze+E/KPoee2UUbQXqvEi6sdT" +
            "pEC7R8A1jCj87PcsZ3/MCUeqHlt1t8KIiK1ytXSf3AcS+6iB4jNai+C+bBThYRabRXvhjP/ng1MFTsuI" +
            "HXxLWzPyDZPwiX9jU1j6Q3K/Fd7Vnqazw03ed3AcQ/NKZ4G5ciyIY1HPX1S7CinhK9pHE/4z2Ynfm49l" +
            "YvkLNLhGk+VJZEeTBdXIeQKayL4ToGDWpzftH+fEOPTfYUuQtI+0WnkkVoFRW+OO7Ts4DKB9ixSVlmlx" +
            "YF1txnQZ/2XQeX15OfOVx2QwhnAwolb2ZvO1O6zyA2q2QRt+XthKS/q1cS5HvagsCqFEeXEjnPICc/TX" +
            "mDb8mDAaZMjx4TskW9PlKW55U9rQ8Fz+dB1D6S687Hmh3PJ7tg0bwZtIggCzHEErJ8OZvEUplTWUvUka" +
            "78jgPIISVA+Urpppywi/OKrVSXa3MWvfsf3dmj81MDk6V0os5YBUEUCprKntatIuf7gOIYxKCJDJYDQ0" +
            "Gn5hG41aclqwST67sS9VIX/ZRvIZdqSuUj7iRTenxjOMoFqFUVsRjdJ3qzI3Hnn0EtBTisHJ1iYETLpp" +
            "J4WemU3znNoorJrB18zWbYNsbZB9K9uhgXpLtxmMjNV0T4jLFZafZspG+Imsme5Ey2pTHfQBVfsXDg1v" +
            "W1A9vSMJQfbTiAkXLB/e5AkQ7q3RVlkPdZYuZ4CG32FiT32EP7bpkawQBPF0n97swhNJlQmiUrHIKaDX" +
            "8BrsSpyYXBfJnWZ7mHfg7Bv23gs/PSB7x5Cu66cksWXAK2y5V1nOym41c8Gq6fSwZX0kY4UbyjGEa5wG" +
            "ESBb4JSIaqgS0LKgsGH6N+/2pyRip3qp2jXfE9/DYpzJTD9hC0syu7Jzz7n9+8zP4XAVYNcqq9ggyQlZ" +
            "pfXKLldXSunDPfQCxlgzHYRZCF1GGGDgYIwmQGFBUwKvVIDAU2y2b4zlg58VHCTf2RbYCuPbxjDNzyqF" +
            "kphXsfioyZjJnpbp54QWAEMQbJKF02QKwNHFXhi6t5zenUJCCs8FCzYyJNG7l6dSzdH4Swhdd1/fZdCT" +
            "d9GV7ofDCIxssbVgylk1k5NupzMNSOPfVCwCJdwIH8UZABYTSbRWhmwivOVH+ig5Y4z88JbbRKU/hpRx" +
            "qpuBYS2RDrGmW1QePDMjsBYDAKCLAgxCHudWEVgitUZGBdt4VOUAMau6+ilIqWypr0XLamc8bAOH4AES" +
            "ARxBvxGFuOfF4aMSBdo0WJUDLiC7xgiNLhZqBTJANMspRCS0XcHQKdH4dKBOb97pwfIBli0ME8Q6u4zH" +
            "IaFBloB2e1UvR77h74oXBYOHUEd8U/mQesRlZaYJMIMjo0zkb/gCIlYuzJ2DELq0QT5tHa6FQarLSqsj" +
            "1KP+DA4Acj8DTdjlfY5Tf18rivenCRGg+uARnT4AkwikH8faeWIY0WqvI5tnhLH4BiNGCg0tk85LdkxE" +
            "BPl3U8xJIvAQgMrAskMnHQ1m8AxCAgoNLsJgnp+NwcARfKWLeZerOsohMHgriJYBw6g0OLsliLXMEeN8" +
            "IUeuzGNc4hMXTk3y8BBDAgiYfB5eAcHxA3sBLbjr8D7zKkQfMI2TI2xM5zHZV1rwFEKTBqTdZrOVv3e8" +
            "FiACeAeYVlgUS49rzk3u8BhBAJOeBsV86IlkMLFnDcXvc7c7AG3gEr3LYCiLNek7+H/fERyYFp/FmK4J" +
            "wYjV3Ne/Y4zilE3gHv8Bu+6jUJzZcEQntl2uz46hCDgnj+0k90JX/xz3lalwPnMspo02XHQUg6AwR3/X" +
            "Iyzahh1/TcQASEOmhu21DUEcCKNXeHsd+s5E7gmKKt0QrgnWmL8Jneuw3nwGG2IlC2NvSY78TXXj7H+d" +
            "rsHsPIsAjiLcQVn5xVAIHtJS4i0VD5yESGoJLsRmqWBLCGIwJJhnYVZeNUc/2tkSAJv51dAs0RA88S0M" +
            "IXgnizbENU0JAS8RflHAtHBkMwZ0QnwduxalvOnzV4W4Mj1Fx+mO/LbgZyayPDeAzYtsgGIOJPU+7Xa0" +
            "zJtp70T0AyukVQbwRhxmhdMvGIYQpLAzgYcPsixlqThWlL7sSQEO0hjDCHAkWQIJbDsLKITKYtDjc8oD" +
            "QEkmLxH76cDeGx6gABz5rHrjeDJG3xV8UQC1WaLcV5/1WRrdVmGvyKoBcqxHP+FEAeVZhrrGrAHKtRjz" +
            "jRwHkWYW5xq4CyLUa8YwfBZBnFeYauwog12rEM34UQJ5VmGvsKoBcqxHP+FEAeVZhrrGrAHKtRjzjRwH" +
            "kWYW5xq4CyLUa8YwfBZBnFeYauwog12rEM34UQJ5VmGvsBsaYYgd7uiaJ8tN2DQA7AVm7re1v1hd2hgY" +
            "YOwEHINjaGdKoFG3XAGOHx0BGAdR2zXfKCw0ARK0P/d4p+lE56mjAPhWYMLy1Tip9rBqoqgET9txmrLV" +
            "m6rpFWzkGEp+QpqQaaEwDHLtr+5ZZy6dgGm8tmZWNZdNUqoFEA8AMsJMsJIZmhSpGNdCUBiqYyaII9q5" +
            "bdBevCZ3UVCGauDs1YMzq/lnLT4bw2VZGEIaXdqc2VOpmNZDHSgagLTNuvNeQuaXZwjR9d2kAGAFWUqk" +
            "zAOGGDc0l/JGcOZ2m0E/VwKAGdlYwkt0ZAqD+mcs2URicw9sbubBbWVq96GYNABOMDcFITg9DAIT7nGA" +
            "V2eCiXBq9VA1w9xRcJNgYpos9AITn/bOXXUfGLB2WVr92qwYYC4KJKvJXBRDS8TTtQp6kLdHurIrWuuW" +
            "WDGWCJQkWqgudrQNVf0zUu2HxAorim/n5pJHS6P2O1MDOyphnVS3pRmyB0kzS74XBXJ3ipxrp/E+pa67" +
            "zamOe4dLXbYHyGaZuPG9eHEVX6Yp1XisddM0rzFgkzK/z1JOuKQClhSXdml1oyJ6tu/ipVvz8ZABsl81" +
            "03ttqpMUZLmUhAKWFwBRk2pPnn2ij6Ay+18dzvSl8ijJH3DaH8rMJaTr9HHsNiPME7N/FhFmsUDfBFmz" +
            "z9Bvuw656UQ7/D0wn1aQ8OdXBAAAAAElFTkSuQmCC")]
        public string ImgVolumeSet {
            get {
                return ((string)(this["ImgVolumeSet"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAAAXNSR0IArs4" +
            "c6QAAEI1JREFUeAHtXWuQHFUVPrd7lncMISCwypqsIQSUp8FAKQhULNFYKV+g5aOKpHiUogHKAgV+CFU" +
            "CClIlUPgKJv7yQTSWKUEs8wMJFqAIgQh5gJu4YFjUkKR4BMh0X893ZnqYmZ3u6Znu3e07c05VMjP31fd" +
            "8/e19nnuuoQxirTWzn71ogQ2CRVzMMJEdJEuDZMyRHDctQ9GaNWcEjDEvk7UvkKHtRIb/0Yjx/Xu2zln" +
            "+CMfZbh9nusk4tGXpQgrseYbsYn7yEd2UoXmKgQATYMySWUO+WTU6d8XaTmvVEYFmPXPhaWEQ3MxMPqP" +
            "TB2l6BxAwZp3n+1dtO/quh9PWNhWBuMUZNoG9xZL9VNqCNZ27CBgyq61vruQWaaSdFm0JVOmuwru5oBn" +
            "tCtP4nkJgJ/ne+e26NS9J5aGNS79GYXgfp1HyJAHVm3Ez8O6FAwn6xbZAQ5uWfJ/HOpcl5NWofkHAmNt" +
            "G5628vJW6LQlUYV14e6sMGtavCHjLRo9dcUez9uMIJGMedFuW/ObE+ruPETAUkOed2zwmaiAQZlsUhI8" +
            "yTDrm6WOuJKiOgfX8+tlZwyAaU3UlTwJ8GjWjypEaErUWSBYJy+WHajH6RRGIQcArlU6PFhtrLZCsMMd" +
            "k0GBFoB6Beq4IgWTgrNsT9Rjp9yQEmCvCGU5TaYF4YzQpvcYpAuMQqHLGg0kGdtXHJdAARSABAbHEAHd" +
            "08JyAkkYlIoDBtFc1BktMqJGKQCsEwB2MgYZbRWqYIpACgWEmEJuhqigCXSFgBz2xYe4qs2bqewTY/t2" +
            "DAXzfA6EAdIcAcwfTeD090R18fZ8L3KksJPY9FApAtwgogbpFTvMJAkogJUImBJRAmeDTzEog5UAmBJR" +
            "AmeDTzEog5UAmBJRAmeDTzEog5UAmBJRAmeDTzEog5UAmBJRAmeDTzEog5UAmBJRAmeDTzEog5UAmBJR" +
            "AmeDTzEog5UAmBEqZcvdC5l1vkn1iB9kRdqM8+grZ514lu3svmT1lsq+VRUNzQIns/iUy0wfIHHUgmaG" +
            "DyAxPI3PiTKKD9+kFFLrWoS8JZDfvonDtdrJ//a8QpxV69Z637e43ififHeMzLJt3NyQXIr3/MPIWsn/" +
            "1Yw5uiOuHH2Zo4wX1WPWuznsCCtf8i4LfjxJte6Wmp9nPJ3PCIfzypxMdxS3LELcwM/ettDjc8kDQEkm" +
            "LtOMNbqVeJXqOWyomkn3yJbKvB7WyaNZB5H98iLzF7yLavz8cvPU+gV7ZS8GqrWTx7+W9lZc9Y1/yP/w" +
            "OojOPIO84bjUGuhwK7g0pfHoX0QNjFPzp30Q735DyzTTu6s6bTT7/o4MG3iJYD37raQKF9z5HwQ83EvE" +
            "4B2JOmkn+54bJnPZ2Ytf++b7OgN2wP/wfCn45Qnb9jkrZPD7yv3wseR87Kt9nFai0niSQfXEPBdc/Tnb" +
            "DSwI1iONddAx53FVNhoTctYXLN9eIZI4/hPxvnUzm8P0n4/GT+oyeIxBIU77275Xu5ND9yP8KtwDorqZ" +
            "AQu7Wgh9wC/i/19lt6b5UuuF9BDL1kvQUgcJ7uMu6dQMRj03QTZWuO4XowCmeaL5apvJ1j0n3hrGW//X" +
            "jyVvUO12aP/2rJ13n/F9EaCm4cyOFP95ExN+9zw5T6dqTiPbpcnCcJyBcB2kBeSYns7YHXyTi7978Q3l" +
            "QlvM4LM96pyzL/RYI5LnmUQr/wi8Gf+FXnkDeR9+ZUv3JTRb+4XkKbnlSWkjvA4eTf+N8djLoNokK8Ce" +
            "a7SVijCHk4RlP6fbTC0seaAlio45YvUadZXyUTf0pz+00gTDmCX/FV1pxy1O66VQy7y2+g33UEXVFnVF" +
            "36OCyOEsgzLZkwMzoo9tygTwRUVBX1BkCHaLlhijepU8nCYR1Hpmq82wLA+aijnmSiIA6o+6YMUIX6OS" +
            "iOEkgLBJi2wBTdf/S41zEXeqMusuqOOsiOjmoiXMEwvaENPm8SCjrPC5PYrjuogPrAp2gm2viFoGwMYq" +
            "9LRasME/5ImEeb5sXOkUXLkt0Yx1dEqcIhF11bIzK3tZEb0/w9kNw21NUXrpuwlsGLDRCJ+gmOjrEIHc" +
            "IxPY8MMmAYGN0woQtEcMVW2jv5++n8NdsAvLMbgp+snnCHhcVHOkkOrKurogzBIIxGOx5zMm8sz4Ru+p" +
            "sVheysRmIE6zcQsREqskO3gydYIFOaIWgI3R1RZwhkFgSMqo+pr45S8imreUL/kzBd3mbATvnUySwVYJ" +
            "Euk5RNTp67BRvVaerK2yYxQyVTSJk2psuW9tUMKQP73yaQKAk8T7BJqqTIKIb6whdobMLNtZOtEAwgIe" +
            "IGWoeloQYIHNrg1YnDXlggiHC3Vxw4xMU3vd85XcH/yMP8vLNAPHCuomOnCLSOT5xMWLcaIGiFoJtmDM" +
            "JBsi/GBGz04YxTkyhaHnqyVO+YT3ZPzJ57qus13jnptv1r5BnfYU8lu9Tv4ZNTeLWr6Dj3WwWC50vjal" +
            "YgYKLTyCc2+KuBqcnxAC+S/AwQA5+yoPjlGOcBvLwM4ObnqiQB8+XlogJwdKORA3k4fTSerEdkH/NiZK" +
            "/+T/oGLKu0FlsuQt+7qzwXRgO/UFw9AY72N1KpwNkM+dtDY8yp/A6TX2rUSWREKIh5Vs/mskjMVyGlPV" +
            "WssZvrKM5vmJVEOnemKBYv7p/I5Okh/wl8rPk3FbaZ+K4Ddsjly9+MG2OcemC721oWEBESzOu60kgURx" +
            "5UEa7VsvMO1jqE+k+rnIFCih8F4bjxiJ86K+t8HpN+DvuqtaMEuWwdhN8hwe93CJERvnRiw9urI5nUKE" +
            "W3VkW8oiOVV1rurdVfOoSFJ9AfFYdghOjSRL+ZqvYRcM8IjcBOb69nkyJu5WzK7ditSMRnt1AMARwt5W" +
            "m5UFSSKQrzukXXYpPIHZ0AMFx4yQJYFCfJ3mih7HNdfn6x2jg7EVRSK0LaiBKXUvUMFXvkDx4SKQrnDw" +
            "UXQo/BsKZdAi8YyTKRO4f8anTZokbE2UlD54T6Rrp3vzsIv0uPIHqXawUCTjUpSWJokp20fLUstY5dYj" +
            "CivpZeAIVFTitVwWBwhMIzp0gUUtUqXYx/m8524qqVh0TIU2nEuka6d5p/slMX3gCpR4PTLI/npbk4W6" +
            "r08XGVi87GvtEurdKU5SwwhMIbuUglp07JYl/ybxMK9VJZXtVM4soTRx5MFXvZLExKq/5M9I10r05vki" +
            "/i08g9kkIEc9gCch5n55NA6vOIW/pXKKZ+yWk7CzK/8K7G05+JJEHg+qWA+sOu7NIV/hjLLq0mRtPffX" +
            "h0FKE3cq1FSaOv2Qu+V+cQ+H9L1BYNYFtmy8mgf+lOeRdzC1bVdqRJ0oHEkHi1omi+Cj9uM+qrjXdxyU" +
            "oTkDxCcTeUCHNzi0TIaxuP0RbEIlpYyI9JqK0ZtX4tOSJiotI0g2J7KZdUgwceBZdit+FwZUuC1yjZFl" +
            "p9r/BR4n5/FVqwYC4TuxjbBVQv56YYp0nrjuTsurKbvjKq+l2w04JEjfCDZHF+1F4AsGTBf4S4Q1VHFp" +
            "2iaHH3lMHfn5WpVVpt6rNz8DJDDGurz7Pv/rE2hZGJ3tbzSSS31xWnEBH6CqtT8FtgaCDEw6m7PbXyP5" +
            "jJ3ns8dQsOCwO+/bh6Nr4VIcP/0HsOQxHdpLEPs6tDrc0yCOfZ7C14Nge8s7n8/gprRFRPmyLzJEHkOH" +
            "6j5ulNVVAvMk+xbp+hAfk7H+66OKEgykYmJcvfFD8DA78diHTvql/6RJl2NukMqrnmR0G5xMuvOe295N" +
            "r5dx/6a4PqlF9XoDL6QR24g2HCnClm5egm/BvXSD/kgas6M4mQ0Q3+JpmXV04kQFMij8Gqr45eICHwA9" +
            "z3oKuovSzD1HHA+2cKxLpFumac/ETUpwzBML1AfAADyfe8MOcu2CsEzfQznFhMq7e0Am6QUe5KiEuYcH" +
            "CnSEQ7p7A9QEQOPGeMOEZGsY7MmP7zGwyR08n/5IJPItfVSTSSXSc5H29LFgWfiGxXjncPRGu3lZphdh" +
            "oPstCYX25Lb/DSfll72kZlXcgDgDI9Qg8bZf7NfJ+wASW504LBBAwDea7JyDi4ZSn4s4L6xB5axXdHLu" +
            "cxS0CMVtwcYlcF8AHBOEBvmF12DU28cq26MC6QCcXL2VxjkDgCC4uwd0TcjsOO0dwVQKuu0zdWRfRyUF" +
            "FnCQQbr3BxSU1X8vsAd41gdf6mo9rXMLi6E0+ThIIZJErlKpeM3B9ALY6XBHUVa484ArDeYPLN/g4SyC" +
            "QBbfe1HwtX/03J0gE8pS5rrAsEB/Xjt/c4zSBQCK5D4wvLoEni/KyhwhdQ1EFdUMdUVe5bAWeZh0XJ3b" +
            "jEzFmVyneOYPs05CdcGI1d91Y5TqlU3knO58918THp4qESSs8of2IXRRXr6Pyv8kmHY7f1APdndiNT/W" +
            "SOJFeOJcWqfzS9RSBAAs8vuuVl/kRpF1JPUcgIZFeutvuvecW35MEitAZd+03rBHZTbB4Q83JKC16FkX" +
            "XfvMdYGLJiAjsbem13zWI3PyC+zX4eI+YirITbxGs/OKqBHZoKX4X2dS1K+GpuNhpPzBGAW+IwuANApM" +
            "M7KrLxqhje1ud4tDTLVADGDxLgwd4ceLNfpgjgfNO+F8UF3rsGQzOneCfB8eKo7PpOKuO48Y4MSqH/vj" +
            "cFo4ZyayPDeBrwpaEMAYTex6HTDJq9e/iS/8QqA4c2FjDDzNc6Wb1QwhTWMMWjd7CQWfMUOugyPy1Lwn" +
            "UgBrcCLMnWBAJPgnhVg6ewaTF4ZYHgpZIWiQ+p4/jxjgxKsTBmTUHjt406JvzDyVQzoD2W3Fdjh77DSb" +
            "VNw4BJVAcMhqeCgElUCqYNFEcAkqgOGQ0PBUCSqBUMGmiOASUQHHIaHgqBJRAqWDSRHEIKIHikNHwVAg" +
            "ogVLBpIniEFACxSGj4akQUAKlgkkTxSGgBIpDRsNTIaAESgWTJopDQAkUh4yGp0JACZQKJk0Uh4ASKA4" +
            "ZDU+FgBIoFUyaKA4BzxjzclykhisCSQiAOx5Z+0JSIo1TBGIRYO7whei0PTaBRigCSQgwd3gMZJRASSB" +
            "pXAICBgSi/F2/JzxSo3oJAftPz/j+Pb2kkuoyeQgYv3SvsdaaWZuWbGcfSHyXkYoikA4B9t01tm3eykF" +
            "M460lsyZdNk2lCFQQAGfAncpCom9WKTCKQEcIVDlT8yI4tGnJA7wmdEZHhWji/kTAmHWj81aeCeVrWxm" +
            "e71/Vn2io1p0iUM+VGoG2HX3Xw4bM6k4L0/T9hQA4Aq5EWtcIhADrmyv5wx2X75EW+jlZCOyscqT2vAY" +
            "Cjc5dMUK+dz5vb9S53aql1S/9jAA4wdwQjtTh0EAghHOCtWS9K+rS6FdFgLsn7wrhRhMW4wiE+NFjV9x" +
            "BxtzWlFZ/9isCzAXhRAv9WxII6XiadjlP0pZpd9YCtX4JkqGMt6zChdZK19aBWkcTDW1ZupCC8G6OnxG" +
            "XRsN7EoGd1THP2iTtYlugKJP0e743X6f4ESK9/ynvmt95qzFPs/ZtW6D6DLOeufC0MAhu1hXrelR66Du" +
            "vMGORsH6dp512HREoKqzSrdnzDNnFuosfoeLmJxNgTDbTeW8rTYvTrGVXBIoKgSnI7GcvWmCDYBGHDfN" +
            "cb5BvUWaP2+ZIjpsWpdPPqUdADk/A/l1MmMUKdQS2YFvnLH8Eu+rd1vD/2c4RAl6ibQ4AAAAASUVORK5" +
            "CYII=")]
        public string ImgVolumeMute {
            get {
                return ((string)(this["ImgVolumeMute"]));
            }
            set {
                this["ImgVolumeMute"] = value;
            }
        }
    }
}
