//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarRaider.GPMDP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgNoToken {
            get {
                return ((string)(this["ImgNoToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgNoConnection {
            get {
                return ((string)(this["ImgNoConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjQzLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0ODozNS0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0ODo" +
            "zNS0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpjNDY3YWRlMy1kNjEwLTk5NGEtYmU1ZC1kZDAxMmNhMjQ1OWYiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6YzQ2N2FkZTMtZDYxMC05OTRhLWJlNWQtZGQwMTJjYTI0NTlmIiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6YzQ2N2FkZTMtZDYxMC05OTRhLWJlNWQtZGQwMTJjYTI0NTlmIj4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDpjNDY3YWRlMy1kNjEwLTk5NGEtYmU1ZC1kZDAxMmNhMjQ1OWYiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6NDMtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz6C0IE1AAAQrklEQVR4nO2dX3QUVZ7Hv7e6uqu76U66k6ZDEgMYmF1BEBOyEQb5sxIFxyPggOw" +
            "57qqjMj6A/FsCPMxxXzz7gJBBQNhzEP8wszN7DgoKji444OHvilkIIgjOChGJTUjoJJ10p/933X2odHe" +
            "UQEhVJ1033M9TJ52q+v2qPrn31q1b9xJogFJKwm9YH4rH6BMASkFRRIEiQlBIKbVr2TcnsxBC/JSikQD" +
            "XQHANQL1oJJ+YVwS/JIRQ1ftVs1GwRqqKJ/A0KJkD0GFqD87RA+Q6CN0nGvC+dVXkYJ+37ssfhzZaJiX" +
            "i8uuyjKl9PRBH/wgCjhlEYY1lZejknW5zRwIFa6TSuEzWQ6a/Vh8ehxkEskcU6Grrqkh9b3/aq0DBGqk" +
            "qHscuAM6MBMdhhTZRxMLeqjXhdl92bJCWygnsB5fnbsQpJ7C/Y4O09HZ/dMsSKLBeekOWsTzzcXFYQxC" +
            "wybY6sqKn73oUqGODtBQJbO7XqDhsYcCynOrIlp//+iaBgjVSlZzAfpnCMDCRcVhAIEgIBsz+eZvoJwI" +
            "Fa6TSeBynwNs8nJ5pE0VUdL87+0kjOi6T9eDycG6Ns8uRFKkSKLTRMikWlb8Y+Jg4rGE0CZOTnY2pEig" +
            "Rl1/PXkgclujuigB0NZz54wnOHSLLmBqskaqALoHiCTyd3ZA4rJF0RqCUEuWpOofTByiZQyklhDeeOWo" +
            "xmoTJQtdgMA6nz8Rj9AkBQGm2A+EwS6kAiqJsR8FhFIoigYILxFEHBYoEQlCY7UA4bEIICgX+9gRHLZR" +
            "S+21HJHI4vcEF4miCC8TRBBeIowkuEEcTXCCOJrhAHE1wgTia4AJxNMEF4miCC8TRBBeIowkuEEcTXCC" +
            "OJrhAHE1wgTia4AJxNCFmO4Bs4w0b8FmzHbV+Cy74RDQ3JxDxJ4BwHHIwDgAQrCJgFiHZDXC7DRjriKP" +
            "SHsJjbj9c5kSWM8gupGOdpHqSaVY55TXjzYZ81F2SEbkS0LQvaaQN5aMFvFLSggpXOEMRssNdI1AwRrD" +
            "u8lDsPisgdrUz9XtiNiDvPjseKEhgvD2MMlsIxeY4bMYEckzKqemIEgRiBnjCIs4ELDjnN+PrJgNav/W" +
            "DhtMlkHH4EMyfIGPtqBuwGu+K0zr4BeqICHj1UgEOHIuA+mMAAOKUUDnRjBeLWzHFFYJRUHcKYjLBCa8" +
            "F73jyUHs6DNoWUfZvN2LWVAmvjW5CjiRnLBc9MqgF2lKfh62HCKgvCgDIGZeLteM78FSxHwb1y0P0SII" +
            "SfOixY925HHScbwcAEIcJS2ZSLC1tzeix9MSgFKghYMC8w4UIXFQuZM64XGwob8H0gtCAHP9IkwXVdfk" +
            "pkWxjcvHRjEaU2AZfg3vQCXS0yYqXP7aCtkVAXGZUPxLHohFtWYllxw9ObPhcBPWGQZwStj8ZxLSCYFZ" +
            "i6S8GlUCb6vOxbV8ciMnIL3fgwDQP7MbstkH8MQGzjhajpc4HGAUsniNieWlLVmPKJIOiI1GmwPNnirF" +
            "tdxSIyZhUlYMTVQ1ZlwcA7EYZJ6oaMKkqB4jJ2LY7iufPFEMeJP+2zAskU2D64RKcPNgBGAUsW2DEzjI" +
            "PMtxG1gShwM4yD5YtMAJGAScPdmD64ZJBIRHzAr3wVTGaT/lAHCa8/UwUS+7V7x3Pkntb8fYzURCHCc2" +
            "nfHjhq+Jsh6QZpgXaVJ+fKnl2zA3iYffA3GVp4WF3CDvmBlMl0ab6/GyHpAlmBTraZFUazACWzTUwIU+" +
            "Sh90hLJurLEWybV8cR5usWY5IPUwK1BAw4OWPrakGs56rrVux5N7WVMP65Y+taAiwubYNkwLNO1wI2hZ" +
            "BfrkD75V7sh2Oat4r9yC/3AHaFsG8w2zO88WcQFvq8xC42A7iMuPANH3dbfUVQqHk4DIjcLEdW+rzsh1" +
            "Sn2FKoI6IgK2HlPVhqh+J66KfRyt2o4zqR5S23NZDBB0Rpi4JWwK9eqkA1BdFzrjcfn880dgp4pm6ezB" +
            "hT1G/lwyLRrQhZ1wuqC+KVy8V9OuxMg0zAgVjBAeOKcMlNpT336OAYJRg2fkizHjXjtOH2hG+7MfWw/3" +
            "fwE3mdOBYBMHYHa3GrguYEWjd5aGg/hhyxuX2y1N1SoBNl/NR/icXDvy3HwjF09+19P9Iw+kFIaUU8se" +
            "w7vLQfj9epmBGoN1nlVDXju/I+L4/abRhwq5CbNsTBfX2TZaZx4bjvrfyseqbYaAaC45kbslcWYCJSE9" +
            "5zYhd7QTJk/BUsT9j+z3XJuGXfy3Bv/4nUT02uulaFNQXxV8+7cSTXwzXFM9TxX4Qp4TY1U6c8po17Wu" +
            "gYEKgNxuU7v7KcnNGRhI2doqYV1uCBW+b0PKVr0/bPnp8OMZsz8fWrob1bytiqe++O9aGmksu1XEZCEX" +
            "lREWcZM56hwmB6i4pt+svFmvrce7eQL54xAeocPHqWT/k9ig274nhUNMQLB/VgoIKR+r77fsT+K7dqDr" +
            "GZI7JnPWO7gXyhg2IXAmAmA2Y4lLfeL5VA7mvlE8aonygwPLDdmUs9GQPBFdXlROK47kv1d+KT3GFQMx" +
            "Kzt6w/h9v6F6gz5qVlRjy7rOrfnsCgKoGck/8xzgPhFwTACB2tRO/v5yPfLOM1x5N77v1bDtqb1hU7d8" +
            "oUDj/3gYgnbue0b1AtX7lQjxQcOcD0mMywY4fnCjbm/nxNg6J4tl/TJ+2P55RqqsF9/hhGZ2+4NXn1be" +
            "FJgxTqq9k7npG9wJd8ClvX4+39156NHWKWP5NIca/58L6XXEE/y/zt/wAsGKEF7AqcUWuBHDSq1zoNRP" +
            "TA+ab6trRrvKxRDLXZO56RvcCNTcrJU+Z7fbtn3//zo1pbw3B/k8D/d7xZzVR/N1EW+rn3TdyAQALitt" +
            "BzF3tFplib1OOqv0nc03mrmd0L1DErzR4i823b/j+4YAyoH6geLwg/Xr0CY9SjZkMFK7709XYnuvq2jD" +
            "JXCN+LpB2ut49txl7OZmhgT3Z0x1pgTqa031BkwvTnxua1AmdyjWs/m5xoNC9QMkpVpITHegFd7dpXWL" +
            "t0dTnkeb053C7OgGSuSZz1zO6F0iv2IzdLm63kqK7QImuyRYGM7oXSOi62+mI6muIQ3s03clH7KbU5zh" +
            "Nn1IqqIs5mWsydz2je4FgVk5iINZLr6xlYHttLwXS0phy048uroTTn41OSdW+U7mauUCakezKyfSEb38" +
            "yn5tlAowDl85nrelb9HvuScd2JZQWy5yrToBkrsnc9YzuBXK7lZN4JnD7Xtnf/aIZR3/bidm/soHk9/9" +
            "QiP1X0iXNzG7vpH3hSUtzr1vdvpO5JnPXM7ovI8c64vgBwDl/71IUDIlj0/2NiI0h2NngwNavrAAyN34" +
            "oyZUOI9rPKXP/wEDwbJEPgPK0v+1Cuvf7nwrbVe1fyTWGsQ5+F6aZSrvy3/11053/NxoFikUj2nBmbv+" +
            "8M/bKhfQ7XO6yXLgtyoX+o8eZ7sw0Cpjt7uxp8145e125LMnc9YzuBXrMrZQgrd/6EZPV34kt/rUJxKW" +
            "9arvok/Dd8fQbITXjvACUMdVbvky3f0b8Qw5spr53JMZkgra/KaMjk7nrGd0L5DInII20gYYTOOFV/3R" +
            "6+agW1P2zF7N/ZQMs6mvuP113pAaijfilE5VDlVLirfo8xBrSJc7Gsc2q9n/CawENKzmzMAe17gUCgPL" +
            "RSpjveLS9n2U1UWy6vxGHX/BjzHQHoKJAm+/ygTgl5I7PxQcVPwIAPJ0GbPxremdFDzlxv1NdJ2Iyx2T" +
            "OeoeJKF8pUd6Zqj0dRkLrqw8ACofE8VFlAz54KYr8Bx192rbMFcG3i7yonf0jciQZlADzjhZC7nqcQXK" +
            "M+K8KdW2vBCWoPa2MJEjmrHeYEKjCFYZx+BDQtgg+9GRulN54ZwT/82gDfv8vFNJIW+8b9MDvLg5LzcY" +
            "KAP/2uIxhVnVVz4ceO2hbBMbhQ5iZ9Z4JgQBg/gSlQbrunLoxNrfjicIAzi5sVNXQ3vNFWpbJVTl4Zrh" +
            "PdRzJ3JK5sgAzAq0ddQPEbkTH+XYcacr8UE9Cb93Qvp1UjmIziMuMZ+da8F6Z+m6DI00WdJxvB7EbsXb" +
            "UDdX7GWh035GYxGqkmDVVwv5PY6iuy8f/Pv5j/xynq6HdOFLEqr8NwzdXZLz84K2rk5OPNWTkuNV1+QD" +
            "aMWuqxNQ6G0zNE90REVD5ByeoL4rVC8WsTSCeaXb84MT6XXEQhwm1z7Uxtb4GM1UYAORIMpbMVHzf8Lk" +
            "If4yp8HvEHxOw4XOlIlgykzIlD8CYQACwtLQVtjG5oN4wZh0t1jyhQTahBEoO3jBsY3KZXJSFOYEA4KM" +
            "ZjSBOCS11Pvymjt25ln9TpyyBQJwSPprRmO1wVMGkQCW2BLY/mZ5reev37M0tuPX7vNQc19ufDDK7kg+" +
            "TAgHAtIIgFs9R2g6b9yZwvFn/b3EmOd5swea9ijCL54hMr+DDrEAAsLy0JTXX8qK9ViYkOt5swaK96Tm" +
            "uWV+5h2mBAODdBz1wVzhAfVG89GeTrquzrd/n4aU/m0B9UbgrHHj3QXbnuE7CvEACAY7MSC+ntPmDGJ4" +
            "/o6+7M0qU5ag2fxBLlTxHZjRA5UsbuoJ5gQBFop1lHiyeb0o1rKccLNFFP5E/JmDKwfRyVIvnm7CzzDM" +
            "o5AEY64m+E/iSlwPLoBMI4IvuDiSDUqAkfNnv/mdQCwQoD2BfvVSAA8cioH5l5gzilFA50YwXi1sxxRV" +
            "SPXVeTCY44bXgHU8eak+HQbvehSd2I2ZNlfDa6Cbmnm31lUEvUJJgjGDd5aHYfVZA7Gp68DsxG5B3nx0" +
            "PFCQw3h5GmS2EYnMcNmMiNUtGR5QgEDPAExZxJmDBOb8ZXzcZ0PqtHzScrpaMw4dg/gQZa0fdYGpIhhb" +
            "uGoG6c8prxpsN+ai7JKueYDyJNNKG8tECXilpYWYYaia5KwXqjjdswGfNdtT6LbjgE9HcnFBmBgvHU/P" +
            "zCFYRMIuQ7Aa43QaMdcRRaQ/hMbefiVdv+pO7XiCONrLf08ZhGi4QRxNcII4muEAcTXCBOJrgAnE0wQX" +
            "iaIILxNEEF4ijCS4QRxNcII4muEAcTXCBOJrgAnE0wQXiaIILxNEEF4ijCYEQov/59Dm6hBDiFygFmzM" +
            "bcbIOpWgUCHAt24Fw2IQA1wQQLhBHJQTXBAD12Y6DwygUlwXRSD7JdhwcNhFN5FNCKSX+1y3XADos2wF" +
            "xWIJct68JFQmEEApC92U7HA5jELqPEEIFABANeD/b8XDYIulMaqK1wHrpqCxjavZC4rCCIOCYbXVkGtD" +
            "tUYZBFNZkLyQOS3R3JSWQZWXoJASyJzshcZhBIHssK0MnUz92/04U6GoAg2MNJU5/0NblSIqfCGRdFak" +
            "XRSwUCO7uSW84NyEQJEQRC62rIj/peL5pOId1VeSgLGDlwIXGYQFZwErrqsjBn/++x/FAOdWRLYKATf0" +
            "fFocFBAGbcqojW3r87lYb2VZHVsCAZbw6u3sRCBIwYJltdWTFrf6m1wn3gzVSVTyOXQCcmQyOo3vauto" +
            "8N1Vb3el1SKt1VeSgKKKC3+LfRQhkjyiiojd5gDsogboT2miZlIjLr/Me68GJIOCYQRTWdO/n6Q1Va8Y" +
            "Ea6SqeAJPg5I5/Ck+65DrIHSfaMD7d1Li3LS1lkNTSkn4DetD8Rh9AkApKIooUEQICimldi375mQWQoi" +
            "fUjQS4FrXKNR60Ug+Ma8IfkmI+oVD/h+S/BTSLP5cMwAAAABJRU5ErkJggg==")]
        public string ImgVolumeSet {
            get {
                return ((string)(this["ImgVolumeSet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjQzLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0ODo0MC0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0ODo" +
            "0MC0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpmMDVjMWQzYS1hNDc3LTAxNDUtOGM1OS05Zjk3MjllYjdmNTYiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6ZjA1YzFkM2EtYTQ3Ny0wMTQ1LThjNTktOWY5NzI5ZWI3ZjU2IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6ZjA1YzFkM2EtYTQ3Ny0wMTQ1LThjNTktOWY5NzI5ZWI3ZjU2Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDpmMDVjMWQzYS1hNDc3LTAxNDUtOGM1OS05Zjk3MjllYjdmNTYiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6NDMtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz4/ueC3AAAPxElEQVR4nO2da3BUVZ7Af+d2d/phd5JOYiLJBhV01xcwRJZREWE1KxaOqIPywdn" +
            "yvW4VDKALyIctP03NBwTWiQi1ZeGzduaDCioWrrho8RBlKAwqjrorxJFsiIkJHdKh053uvmc/XG4nQJ5" +
            "9u+l7w/l96+77+P9vfjn3nHPPPUdgASmliP8h8MtUUt4JTEJSLaFaCCZIKUNWjq3ILUKIqJS0CjiO4Dj" +
            "Q5PaI7b4nY38WQsisj5vNTrH13vpUmvuRYgHIS7I9ucIOiJ8QcpvbxZuBFYmdY957LBv3Pue/IZ3Sn9V" +
            "1Zo/1RAr7o2nsdbm1p/1P9e4f7T6jEii23jsppYu16PLX2YencAya2OrW5KrAikTTSJuOKFBsvbc+leI" +
            "NIJyT4BROIeJ2s2ik25o23I/d67xL9TQfoOS5EAnraT7oXuddOtxGQ5ZAPWu9f9B1luc+LoXT0DQagqs" +
            "STw7226ACda/zLiXN83mNSuEsXCwrXpnYcPbX5wgUW++t19N8oEtc5ycyhRPQBGnNxR1n14nOECi23js" +
            "pleIgqs6jGJyI282Mga2zMyrRKV2sRcmjGJrwaUcyZEqg3uf8NyT79M/Of0wKp+Ep0m40OxszJVA6pT9" +
            "buJAUTmKgKxqcrjirxxOKUaLrzI6t99bDaYFSae4vbEgKp2E6o0kphfFUXaEYA1IskFIKoSrPimzxFGk" +
            "3aqcHgykUYyaVlHdqwKRCB6JwLJM0JNWFjkLhUCTVmkQJpMgOCdWaEEwodCAKZyIEEzT19oQiW6SUoWF" +
            "HJCoUI6EEUlhCCaSwhBJIYQklkMISSiCFJZRACksogRSWUAIpLKEEUlhCCaSwhBJIYQklkMISSiCFJZR" +
            "ACksogRSWUAIpLOEudACFpiPu4sP2EAeifr7pctPeniYRTUM8hR5LAaAF3OBz4w25qKx0cU1pipmhXm6" +
            "vjFLhSxc4g8Iiutd4s55k2qkc7PDxQnM5jUd0En/tsXQs72VB6q7Q+G1tJzMq4jmK0DlcMALFkoI1Ry9" +
            "my5cayWOnMt8Ln4uyq0JMrUozJRRnerCXGl+KoCdNcZFxabr7BD1JFy1xN4d6/ByO+viqzcWJ76LIeH8" +
            "J5Jl4EQun6aye/DMBzwVxWce/QN0JjWeOVLFjbwIZTQIgwl5mXu/j0ZoTzKroxaNldwmSumBfh5+XW8o" +
            "48HkcGUkYxw95mDfby++uaKPYq+csFzsyrgXa0FTGxo8EsqsPgOLrSlg9pZt7a6K4sl8eYlDSUvB2S4g" +
            "1h4vp/vokAKK0iCW3SZZOOpHTc9mJcSlQc4+Le3ZNoOdb4w9ZfF0J6+o6mVPVe17Ov7vNz8rG8oxIwat" +
            "LeGduK7XB8VfhHncC7WkL8MR7AWQkgajwsfLWFI9fGilILJt/DLPuYzeyI44Ie3nxrhi3VMUKEku+GFc" +
            "CNTSVs2lbCpI65XWl7LilhZCnsHWQaFJj3p4aOhu7wKOxeIGb5ZM6CxpTLhkXHYm6hIcO1bBpSx8kdW6" +
            "oL2ZffXPB5QEIeXT21TdzQ30xJHU2benjoUM16OPk39bxAukS5uyqZf/ObvBoLLvPw2vTW8hxHdkSQsJ" +
            "r01tYdp8HPBr7d3YzZ1ftuJDI8QI98kUN7Qe7EKVFvPRAH0sut2+LZ8nlJ3jpgT5EaRHtB7t45IuaQod" +
            "kGUcL1NBUnil5Nt8d4+bK89PKssLNlb1svjuWKYkamsoLHZIlHCvQnraAUWEGlt3tcoQ8JjdX9rLsbmM" +
            "pkk3bUuxpCxQ4ouxxpEDNPS6eeC+QqTDb+bY1FEsuP5GpWD/xXoDmHmeubeNIge7ZNQEZSVBeV8qrdS2" +
            "FDidrXq1robyuFBlJcM8uZ87z5TiBNjSV0fPtSUSFjx232Ku1NVaExMihwkfPtyfZ0FRW6JDGjKME6k5" +
            "obPzIWB9m5a0pW/TzWCXk0Vl5q1GX2/iRoDvhqD+JswR65kgVsquP4utK8v54ovWUmwca/4ZpW6vzXjI" +
            "8fmmE4utKkF19PHOkKq/nyjWOESiWFOzYawyXWFeXv0cBsT7Bsq+rmftKiM8/Okn8aJSNu/JfwTVz2rE" +
            "3QSw5qtXYbYFjBFpz9GJkNEnxdSV5eaouBTQcLafujxXs+K8o9Kb6f+vM/0jDOVW9RikUTbLm6MV5P1+" +
            "ucIxAW740Ql09pTvnx97eGmTaGxPYtLUP2VG4YalmbmauTsARkR7s8JE8dgoR9nJvTTRnxz0c8XLTf9f" +
            "yr/8phh0bPXVuSc7OORz31kQRYS/JY6c42OE7L+e0iiMEeqHZ6O6feb0vJyMJW0+5uedALfe9VETnF13" +
            "Dbjt1bglv/v3/AcZt7lf7J7Lph7FXqjf9UMav9k9EDlO9cQnJzOsNccyc7Y4jBGo8YjTXH62x1uM8sIL" +
            "87e4uGMHFs+WZ/2kt3++N0LAlOSaJNv1QRsOWJN/vjXDnp7XDSmTmaOZsd2wvUEfcReKvPQifi1kV2Ve" +
            "eh6ogD8VAeQDu+mwiTZ90GR8ko5bIlMeU9egnXdz12cQht59V0YvwGTl3xO3/eMP2An3YbqzEUHZVKOu" +
            "3J4AxV5Bnhs/cdn5Vz4A1rhmVRGfLA4A4fawh8GiS8N8Fgf7c7YztBToQ9QMwtWr0A9KTumDzj2Gmv5v" +
            "9eJvNbyfO6EBcfPkJli/0jFqioeRZvtDD4hEe/k67xLh9mbnbGdsL9E2X8fb1lNDIpUfbKTfLvq5myqs" +
            "VrH0jRex/rTX5X9iaZPOP4czn0UpkRR7oz9XM3c7YPsL2dqPkmR4cvv7z++8reX17ApK5a+YjYe1baYr" +
            "uL+XBiV2AIRELzxLktEQsNCSyIg+YubozudsZ25dAiahxEWt8w1d8X99hDKjPObrk92+dedzhSiKr8kB" +
            "/rmbudsb2AhE3LmbQM8LF7M3jxU6fW3kfSiKr8sCAXOMjtxYLje0FMqdYMSc6sBODSmSSpTzQn6uZu52" +
            "xvUAKe2N7gbSAUc/v7rPfEIdBW1smY+hsPBszVzN3O2N7gfAZF7EnOUKvrP/89toO1VQfa2fjYGRy9Sm" +
            "BLOMNGRezJT78xXxwXhF48pPOjfXFZ3werp9nLJ2NQ2HmauZuZ2wvUGWlcREP9QzfK/tvV7az559Pccf" +
            "8IKI8d0Mh5txezKvT+9/8GKmTcKw91oNh5mrmbmdsL9A1pUZL5HB0ZCmqLkrRcG0rhx/uYNUiN4G/LR5" +
            "xn+H4h3khXpw2enlMrEpk5mrmbmdsL9DMkNED/VXb6P8bPZrk8UsjHLo7+3fG5s0P8h9Tj2c+j/XxhBW" +
            "JvvzJ+LOYudsZ2wt0e6XxaOLEd1GSevYtscW/LkJUjP7WdvaZ3m8LjrmTcCiJ3m8LDrlPUhdE/sd4Wm/" +
            "mbmdsL1CFL433siAynmZfR/ZPp5dP7qTxNx3cMT8I/pFbNx+838Pyv/S/LfrejceYfHOp8WEMnYRnSzT" +
            "55lLeu/HYkNvv6/Aj40bOTpiD2vYCAdRdYYT5cou197MCRZKGa1vZ9UiUq+eUDt6DPICBEgkJ229q5sr" +
            "Z4TH3MJsSXTk7zPabmod9m9bM0czZ7jhiiruDHT5+84oHEfbyl8c6czbD6uGIl385WDniuOg75gdpuLY" +
            "1J+ccjrQUXPtSOTKS4I+PJB0xcbkjNJ9REccz8SJkJMHbLbkbpTclnODTf2zm3/9J4r1s6HrJB+9bm81" +
            "+tLzdEkJGEngmXuQIecAhAgEsnGYMqVhz2FrTfDDunNDDl4tax1zRzjVmbmauTsAxAq2e/DMi5KH765P" +
            "sbsv9UE8hh65o57Jjcih2t/np/vokIuRh9eSf836+XOEYgQIeybzZXgBWNubvnamBFe3rbyvBNznE0rn" +
            "5bw2ZOc2b7XXUOhuOqESbdCc0Zr4eRnb1sWqRu2ATiOeazT+GWftGClFaxIEHI45aX8MxJRBAsVdnyW2" +
            "G7+s+dhNNOir8QYkmNdZ9bNwul9wmHSUPOEwggKWTThC8ugTZEWfenpph3/K0O1Jg5NARJ3h1iSMXZXG" +
            "cQADvzG1FhL10NnbxcKNz51p+uNFYAkGEvbwzN//9TPnAkQLVBtO8eFf/XMsbsxj1V2g2/lCWmeP6xbt" +
            "ijl3Jx5ECAdxSFWPxAqPu8Py7aT5pt/9bnCaftPt5/l1DmMUL3I5ewcexAgEsn9SZmWv58XcDjpDok3Y" +
            "/j7/bP8e101fucbRAAK/8ooXKGaXIrj4e+1ORrW9nG38o47E/FSG7+qicUcorv3DuHNcmjhdIE7B7bv9" +
            "ySs+/leShQ/ZqnUlhLEf1/FvJTMmze24zmo1izBbHCwSGRK9Nb2HxwqJMxXrWzlpb9BNFkxqzdvYvR7V" +
            "4YRGvTW8ZF/KAw3qiR4Na8vL8Mu4EArXo7vlkXApkopb9zj/jWiAwHsA+c6SKHXsTyGgSABH2MvN6H4/" +
            "WnGBWRW/WU+cldcG+Dj8vt5Rx4PM4MmLMpC9CHubN9vK7K9oc92xrrIx7gUxiScGaoxez5UuN5LFTme+" +
            "Fz0XZVSGmVqWZEoozPdhLjS9F0JPOzJLR3SfoSbpoibs51OPncNTHV20uTnwXRcb7b0ueiRexcJrO6sk" +
            "/O2pIhhUuGIEGcrDDxwvN5TQe0YedYHw0eC8LUneFxm9rOx0zDDWXXJACDaQj7uLD9hAHon6+6TKmlUt" +
            "E0xBPZebn0QJu8LnxhlxUVrq4pjTFzFAvt1dGHfHqTT654AVSWKPwPW0KR6MEUlhCCaSwhBJIYQklkMI" +
            "SSiCFJZRACksogRSWUAIpLKEEUlhCCaSwhBJIYQklkMISSiCFJZRACksogRSWUAIpLKEJIew/n77Clgg" +
            "hopqUOHNmI0XBkZJWTcDxkTdVKM5FwHENoQRSZInguAY0FToOhUORHNXcHrG90HEonIm7SLwvpJQi+qz" +
            "/OMhLCh2QwkmIn0JP91ZrQgiJkNsKHY7CYQi5TQghNQC3izcLHY/CWZjOZCZa61nr3aPrzC5cSAqnoGn" +
            "sDa5K3AIDHmW43NrThQtJ4SQGupIRyP9U7340sbUwISkcgya2+p/q3Z/5OPA3tyZXAeNjDSVFPoicdiT" +
            "DGQIFViSa3G4WaYILe9IbxTlogrTbzaLAisQZHc/nDOcIrEjs1DWeOn+hKZyArvFUYEVi59nfDzoeqHh" +
            "lYoOm0ZD/sBROQNNoKF6Z2DDob0PtFFyVeBIXy9Tt7MJFE6RxsSy4KvHkUNuMOOF+bL23PpXiDSCcy+A" +
            "Utidyus5zzm1rICMOaQ2sSOx0u5mhmvgXEJrY6nYzYyR5YBQl0EB6n/PfkE7pz6oe6/GJprHX5daeHtj" +
            "PMxJZrRkTW++tT6W5HykWqKf4Tkf8hJDb3C7eHE2Jc87eVk4tpRTxPwR+mUrKO4FJSKolVAvBBCllyMq" +
            "xFblFCBGVklYBx0+PQm1ye8R235OxPwuR/cIh/w8m2EOd1GQ7XgAAAABJRU5ErkJggg==")]
        public string ImgVolumeMute {
            get {
                return ((string)(this["ImgVolumeMute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAFHGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTA0LTAzVDIxOjAwOjQzLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wNi0wMlQyMzo0OTo1MC0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wNi0wMlQyMzo0OTo" +
            "1MC0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpmMGZhYTJjYS1jMzJkLTI3NDItOWNhMC0wNzFkYzJkMGYzMjYiIHhtcE1NOkRvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6ZjBmYWEyY2EtYzMyZC0yNzQyLTljYTAtMDcxZGMyZDBmMzI2IiB4bXBNTTpPcmlnaW5hbER" +
            "vY3VtZW50SUQ9InhtcC5kaWQ6ZjBmYWEyY2EtYzMyZC0yNzQyLTljYTAtMDcxZGMyZDBmMzI2Ij4gPHh" +
            "tcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ" +
            "6aW5zdGFuY2VJRD0ieG1wLmlpZDpmMGZhYTJjYS1jMzJkLTI3NDItOWNhMC0wNzFkYzJkMGYzMjYiIHN" +
            "0RXZ0OndoZW49IjIwMTktMDQtMDNUMjE6MDA6NDMtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkF" +
            "kb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9" +
            "yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ" +
            "9InIiPz5/jDcQAAAOv0lEQVR4nO2da3BUVZ7Af+d2d/pBOnRISIRMVDJUKRaIBJbB4SElLKxjiTqoH2Z" +
            "212fxAQShePhl/WTVVvEqBcTaonzO7MxOqShgOYoFFvIYGBbCIJa6VRCFVAOJCQnp2I909z374dJN5J2" +
            "+ndx7wvl9Srrv4/+/99fnnnvuuecIbCClFMlXQ7/KpOWDQB2S4RKGC8EwKWXYzrY1xUUIEZOSMwJOIzg" +
            "NNHp94pPA4vjfhRCy4O0WslJ8rX9mJsvjSDEH5C2F7lzjBsRZhNzm9fB+aGlqR6/X7s3CiVeCk7IZc5V" +
            "pMrW3O9K4H8Ngj8drrAguSRy40XVuSKD4Wn9dxhSrMeVvCw9PowyG+NBryOWhpanG6y16XYHia/0zMxn" +
            "eA8qLEpxGFdq9Xp643mXNuNaXnWv8C80sn6HluRkpN7N81rnGv/BaC121BOpa7X/VNHmh+HFpVMMwWFe" +
            "6PLX4St9dUaDONf6FZFnfp1Fp1MLDorJlqQ2XfnyZQPG1/plmls9Miad/ItOogCHIGh7+5dI60c8Eiq/" +
            "112UyHELXeTRXpt3rZULPu7OfVaIzpliNlkdzdcovOJInXwIlXglOSneb+/s/Jo1q+EqMe3ONjfkSKJs" +
            "xVzkXkkYlerpiwIWKs348oblBTJOp8bX+mXBBoEyWx50NSaMaOWcMKaWwnqprNL1AijlSSiF05VlTKL4" +
            "S417jQmcwjabXZNLyQQOoczoQjbLUGUiGOx2FRlEkww2JFkhTGBKGG0IwzOlANGoiBMMM/faEplCklOF" +
            "r9kjUaK6HFkhjCy2QxhZaII0ttEAaW2iBNLbQAmlsoQXS2EILpLGFFkhjCy2QxhZaII0ttEAaW2iBNLb" +
            "QAmlsoQXS2EILpLGF1+kAnKY16eHzljAHY0G+6fDS0pIlFctCMoMZzwBghLwQ8OIPe6iq8nBXJMPEcIJ" +
            "ZVTEqA1mHM3AW0bnSX/Ag06pyqDXAa00VNBw3Sf3QZWtb/ttLqR9p8HxtGxMqk0WKUB1uGoHiacHKE0P" +
            "ZfNQgfeqn/Oci4GHInWHurs4yJpxkXGmCmkCGUl+WshLr0HR2C7rSHqJJL0e6ghyLBfiq2cO572LI5MU" +
            "SyHfrIOaONXnxlz8S8t0Uh3XgC9SZMnjpeDXb96SQsTQAotzPxPEBnqk5x+TKBD6jsEOQNgX7WoO8FR3" +
            "CwcNJZHvK2n7Yx+ypfl4e2UyZ3yxaLm5kQAu0oXEIG3cKZEc3AGWjB/PimE4erYnhKXx6iCuSlYKPomF" +
            "WHiuj8+vzAIhICQtmSBbWnSvqvtzEgBSoqcvDI7uG0fWtdSLLRg9mTX0b91Un+mX/XzYHWdZQkRepdNR" +
            "gtkw/Q23pwKtwDziBdjeHmPdxCNmeQlQGWHZ/hudua3ckljdOlrPmCy+yNYko97PpoTjTquOOxNJXDCi" +
            "B1jVW8Pq2DKRNKuojbJ8WJexztg4SSxvM3l1DW0MH+Azmz/HyQl2bozEVkwHRkGhKePJIDa9v7oa0yaS" +
            "ZZeyb2eS4PABhn8m+mU1MmlkGaZPXN3fz5JEazAHys1VeIFPCfbtqObCjE3wGix7z8e64KEWuI9tCSHh" +
            "3XJRFj/nAZ3BgRyf37aodEBIpL9DT/6ih5VAHIlLCm7/rZsEI997xLBhxjjd/142IlNByqIOn/1HjdEi" +
            "2UVqgdY0V+ZLnjYfjTKnqn7ssO0ypSvDGw/F8SbSuscLpkGyhrEC7m0NWhRlY9LBHCXlyTKlKsOhhayq" +
            "S17dl2N0ccjiiwlFSoKYuD/M+DuUrzG6+bF2NBSPO5SvW8z4O0dSl5tw2Sgr0yK5hyPYUFfUR3qmPOh1" +
            "OwbxTH6WiPoJsT/HILjXH+VJOoA2NQ+j69jyiMsD2ae662+otQmLlUBmg69vzbGgc4nRIvUYpgTpTBht" +
            "3WvPDLLs/44p2HruEfSbL7rfqcht3CjpTSp0StQR66Xg1sqObstGDHXs80Rc8d1s7ZaMHIzu6eel4tdP" +
            "h9AplBIqnBdv3WN0l1tRf+1GAvKHJzN1FLqfte1LE0+okoIxAK08MRcbSlI0efM2n6g/sr2XU+gj/2vA" +
            "L4t3qnIj7qhNWKRRLs/LEUKfDuWGUEWjzUSvUF8d0XnO5xr0dyGSW/915nvF/GcrW02VFjWPyzlruWB3" +
            "mjtVhpnxRW9Tlc7nlclUBJSI91BogfeonRLmfR2tiN7ye2ZxgxZ8ks/bV0posTjtLa0NH/u8fD3dcdbl" +
            "Cln+0JoYo95M+9ROHWgOFBdjPKCHQa01Wc//E8YGCehKe/FsHU/8QYeP37r5N9gjJxPGWOLmc3Y4SAjU" +
            "ct27Xn6kpvMXZPN/N+g/STPq8lu9jJcUKrejkcszl7HZcL1Br0kPqhy5EwMPkSvvPu9qPdvDA2yH+47t" +
            "qV3anmFyZQASsnIt12e1LXC/Q5y3WTAxD7gwX/PbEpchUlvc/jjNuy3AOtQWLss1i4TMk5XeUAhdzdzO" +
            "uF+hgzDrBd1cXv0N68niM37/j46kjNSQyRd98wYy9xbp85XJ3M64X6JsO6+3rMeE+euvTlOzf0cn4/6n" +
            "mr2cH9c0+ekku11zubsb1ArW0WCXPuNK+7e+TPRtnyR8NfrO/lraks4cll2sudzfjeoFSMesg1gT65xp" +
            "zYm8Hk/9Yzhsny/tlf1cil2sudzfjeoFIWgez1Nd/B1N2dLP6vQy/3lHLyZiv3/abI59r0kUVs6vgeoF" +
            "yQ6zkBjroT9qOdPDAlv5vfMzlmsvdzbheIKcxfOo8kHUC1wtkhKw7kU4HnqxX3BPhkwf7/y3SXK653N2" +
            "M+yMMeOF8N11pDxWB/mneNwaXsOSfJfNGNPXL/i6lK32hBTrg/tPj+gj9YQ+JZogmvdwWTvf5/uqmRPj" +
            "vcdF+k/VKRJPWafGH9aMM21RVWQfxSFfftsp6bgnxyr+ZfHpvk6PywMVcc7m7GdeXQHdFMpwEjsX6qH+" +
            "MIZh0f5j/GhMl6JKjYeWa5q6I++/CXHLIrs7EcIJPga+ai/9rDIwM8+a0diZUuOvdsqNnrQvDxLD737Z" +
            "1/SVsVpXVA/HcdzHSZnHuxITfw9yHBtHwyBkmVLjrJKVNQfv/WSPH5nJ3M64XqDKQxX97KTKZZV+r/Xp" +
            "Q+dgInz4d5z/vPFv0cRKLwb7WIDJp5azCGNSuFwigfqQV5lvRwluFRZmPRY/5ODCriRHh7mKFVnRyOeZ" +
            "ydjuurwMBPF/bxn58HDycJHuP6HXJcfvkcv5UH3X9LzorBQcPW105nq9VYxg8JTSfUJnEd+sgZHuKj6L" +
            "X6aXXo5pkVAdZ9XvB9l+fKpo8lfWR/N9Dx0euulwhy38UDSPbU/huHaTMqPdKlEAAc8ea/OUUrDxWxmO" +
            "/uPq7YaOmRfj2b53807Qwm0ZHCRX5Iey+GU0wI/ff9Su5vVl+5bEy4Dxzx6rRoR4UGqU1nhbUv1mOjKX" +
            "Z9O+Za76dmpW9v8w5zZfNQeb9wYsI+2h4tl2ZqRKUuIQBhHyS2VP9ACxruPY7U6rJAxdzmj3Vr4w8oJB" +
            "AAC+PbEZESuj8+ryjPQaLzRsny+n8+jwiUsLLI5udDqdXKCVQmd9kwQzr17nmCy+xtFLhX5FY2mDNF1Z" +
            "VdMEMqdzkLMqdgYV15ygdNRjZmmT27holh3LJIQVWDq1JSkcNVnJSFuUEAtgy/Qyi3E9bQwdPNag71vJ" +
            "TDdYUCKLcz5bpZ5wOpyCUFKi2NMumhy6Otez2QROuxMbvh+THuN70UFzZmXyUFAhgWnWc+XOsusP6rVn" +
            "2trj/Lc4ce1uCrN9qCTN/jlfpGXyUFQjghbq2/FjLz20NKSHR3pYgz229OMa16jP3KC0QwNv3RKmaEEF" +
            "2dPPsn0tcfTnb+P0Qnv1zCbKjm6oJEd6+x139kApBeYEMAV9Ovzid0voP0jx5xF13Z1JY01Gt/yCdL3m" +
            "+nN6E4aIYC0V5gcCS6N1xUebPLclXrCfvqHVFO1EsbTB5x8XpqObPLeHdcdEBIQ8o9CzsRtFTXvYvA04" +
            "g0JPu9icDUqAcetrvvmdACwTW/BovHa9m+54UMma9mCjK/UwcH+CZmnNMrkwUPHRe2hTsaw3yVnQIBw8" +
            "nke3WSPoi7GP2VD8vj2xW7tlWbxnwAuWIpwUrTwxl81GD9Kmf8p+LgIchd4a5uzrLmHCScaUJagIZSn3" +
            "Z/CgZnd2CrrSHaNLLka4gx2IBvmr2cO67GDJ58bLku3UQc8eavPjLH5XqkmGHm0agnhxqDfBaUwUNx01" +
            "SP3TZ2pb/9lLqRxo8X9umTDfUYnJTCtST1qSHz1vCHIwF+abDS0tL1hoZLJnJj89jhLwQ8OIPe6iq8nB" +
            "XJMPEcIJZVTHXd9Tva256gTT2cL6lTaM0WiCNLbRAGltogTS20AJpbKEF0thCC6SxhRZIYwstkMYWWiC" +
            "NLbRAGltogTS20AJpbKEF0thCC6SxhRZIYwstkMYWhhDC/ePpa1yJECJmSImaIxtpHEdKzhgCTjsdiEZ" +
            "NBJw2EFogTYEIThtAo9NxaBRFcsLw+sQnTsehURNvifirkFKK2KrgaZC3OB2QRiXE2fCKxHBDCCERcpv" +
            "T4WgUQ8htQghpAHg9vO90PBq1yDmTH2ita7V/t2ky1bmQNKpgGOwpXZ6aBj0eZXi8xgrnQtKoRE9X8gI" +
            "FlyQOYIgPnQlJowyG+DC4JHEg/2/P77yGXA44MyKlRgXaLziS52cChZamGr1enjAEN/egN5rLMARZr5c" +
            "nQktTP2t4vqw7R2hpaodpsKT/QtOogGmwJLQ0tePSz6/YH6hsWWqDYbCu78PSqIBhsK5sWWrDFb+72kq" +
            "ly1OL8bBIX85uXgxBFg+LSpenFl9tmesOuB9f65+ZyfAeMHAmKdXcCO0X6jyXXbZ6ct0uraGlqR1eLxP" +
            "0Lf5NhCE+9HqZcD154AZKoJ4kXglOymbMVbrFemBiGOzxeI0VPdt5rkdBc8bE1/pnZrI8jhRz9FN81RF" +
            "nEXKb18P7N1LiXLa2nV1LKUXy1dCvMmn5IFCHZLiE4UIwTEoZtrNtTXERQsSk5IyA0xd6oTZ6feKTwOL" +
            "434UofOKQ/wf4g1PGdCH+QwAAAABJRU5ErkJggg==")]
        public string ImgPlayPause {
            get {
                return ((string)(this["ImgPlayPause"]));
            }
        }
    }
}
